"""Render docs/METHODS.md from the LinkML ontology + contract (SSOT-driven).

The three schema YAMLs under web/schema/ are the SINGLE source of truth for the
Chronicle usage-measurement instrument:

  * chronicle-research-ontology.linkml.yaml — the entity/measurement model,
    provenance backbone, and external-framework mappings.
  * chronicle-local-contract.linkml.yaml    — the browser preprocessing contract
    (every processing option: key/type/default/description) and the raw-input
    RawChronicleEventRecord class.
  * chronicle-workflow.yaml           — the LinkML-conformant projection of
    phases, semantic operations, artifacts, and physical queries.

This generator does PLAIN yaml parsing (no linkml runtime) and renders a
methods-section-style Markdown document. It never hand-writes definitions: every
class definition, option description, default, and mapping is quoted/derived from
the YAMLs, so METHODS.md can never drift from the ontology. Only the section
scaffolding (headings and connective sentences) lives here.

Determinism contract (mirrors the OWL/SHACL byte-repro discipline):
  * no timestamps or run-specific content;
  * ordering is the authored YAML order where that order is meaningful (option
    list, class list, enum members, node/step order), and sorted otherwise;
  * output ends in exactly one trailing newline.

Usage:  python generate_methods_doc.py <output.md>
Inputs are resolved relative to this script's location (web/schema/), so the
generator is cwd-independent (the Makefile check target regenerates into a temp
path and diffs against the committed doc).
"""

from __future__ import annotations

import sys
from pathlib import Path
from typing import Any

import yaml

SCHEMA_DIR = Path(__file__).resolve().parent.parent
ONTOLOGY_YAML = SCHEMA_DIR / "chronicle-research-ontology.linkml.yaml"
CONTRACT_YAML = SCHEMA_DIR / "chronicle-local-contract.linkml.yaml"
GRAPH_YAML = SCHEMA_DIR / "chronicle-workflow.yaml"

GENERATOR = "web/schema/tools/generate_methods_doc.py"

# Section ordering for the pipeline-stage table (contract PipelineSection enum).
SECTION_ORDER = ["preprocess", "clean", "analyze", "output"]
SECTION_TITLES = {
    "preprocess": "Preprocess",
    "clean": "Clean",
    "analyze": "Analyze",
    "output": "Output",
}

# Mapping predicates carried by classes / enum members / slots that anchor the
# ontology to external frameworks. Scanned generically so a new mapping predicate
# in the schema surfaces automatically.
CLASS_MAPPING_KEYS = (
    "exact_mappings",
    "close_mappings",
    "broad_mappings",
    "narrow_mappings",
    "related_mappings",
)


# --------------------------------------------------------------------------- #
# helpers
# --------------------------------------------------------------------------- #
def load(path: Path) -> dict[str, Any]:
    return yaml.safe_load(path.read_text(encoding="utf-8"))


def clean_text(value: Any) -> str:
    """Collapse a (possibly folded) YAML scalar into one trimmed line."""
    if value is None:
        return ""
    return " ".join(str(value).split())


def cell(value: Any) -> str:
    """Render a value safe for a Markdown table cell."""
    return clean_text(value).replace("|", "\\|")


def render_default(slot: dict[str, Any]) -> str:
    if "default" not in slot:
        return "—"
    default = slot["default"]
    if isinstance(default, bool):
        return "`true`" if default else "`false`"
    if isinstance(default, list):
        if not default:
            return "*(empty list)*"
        return "`" + ", ".join(str(item) for item in default) + "`"
    if default == "":
        return '`""` *(empty)*'
    return f"`{default}`"


def render_type(slot: dict[str, Any], default_range: str) -> str:
    rng = slot.get("range", default_range)
    if slot.get("multivalued"):
        return f"list of `{rng}`"
    return f"`{rng}`"


# --------------------------------------------------------------------------- #
# section renderers
# --------------------------------------------------------------------------- #
def render_header(ontology: dict[str, Any]) -> list[str]:
    title = clean_text(ontology.get("title", "Chronicle usage-measurement instrument"))
    return [
        f"# {title} — Methods",
        "",
        f"<!-- GENERATED by {GENERATOR} from web/schema/"
        "chronicle-research-ontology.linkml.yaml, chronicle-local-contract.linkml.yaml,",
        "     and chronicle-workflow.yaml — do not edit by hand. The schema"
        " YAMLs are the source of truth; regenerate via `make -C web/schema"
        " methods-doc`. -->",
        "",
        "This methods document is rendered directly from the instrument's LinkML"
        " ontology and its preprocessing contract, so every definition, parameter,"
        " default, and external mapping below is quoted from the source-of-truth"
        " schema and cannot drift from it.",
        "",
    ]


def render_overview(ontology: dict[str, Any]) -> list[str]:
    lines = ["## 1. Instrument overview", ""]
    lines.append(clean_text(ontology.get("description")))
    lines.append("")
    return lines


def render_entity_model(ontology: dict[str, Any]) -> list[str]:
    lines = ["## 2. What the instrument measures — entity model", ""]
    lines.append(
        "The entity model is defined by the following ontology classes"
        f" (schema `{ontology.get('name', '')}`). Definitions are quoted verbatim"
        " from the ontology."
    )
    lines.append("")
    lines.append("| Class | Definition |")
    lines.append("|-------|------------|")
    for name, cls in ontology.get("classes", {}).items():
        lines.append(f"| `{name}` | {cell(cls.get('description'))} |")
    lines.append("")

    enums = ontology.get("enums", {})
    if enums:
        lines.append("### Controlled vocabularies (measurement categories)")
        lines.append("")
        for enum_name, enum in enums.items():
            lines.append(f"**`{enum_name}`** — {clean_text(enum.get('description'))}")
            lines.append("")
            lines.append("| Value | Meaning |")
            lines.append("|-------|---------|")
            for value, body in (enum.get("permissible_values") or {}).items():
                body = body or {}
                lines.append(f"| `{value}` | {cell(body.get('description'))} |")
            lines.append("")
    return lines


def render_pipeline(contract: dict[str, Any], graph: dict[str, Any]) -> list[str]:
    lines = ["## 3. Preprocessing pipeline", ""]
    lines.append(
        "Each raw Chronicle upload flows through the semantic operations below."
        " Presentation phases, semantic operations, physical queries, artifacts,"
        " and configuration dependencies are separate projections of the executable"
        " workflow contract (`chronicle-workflow.yaml`)."
    )
    lines.append("")

    phases = graph.get("workflow_phases", [])
    lines.append("### 3.1 Presentation phases")
    lines.append("")
    lines.append("| Phase | Identifier | Purpose |")
    lines.append("|-------|------------|---------|")
    for phase in phases:
        lines.append(
            f"| {cell(phase.get('workflow_label'))} | `{phase.get('workflow_id')}` "
            f"| {cell(phase.get('workflow_description'))} |"
        )
    lines.append("")

    operations = graph.get("workflow_operations", [])
    lines.append("### 3.2 Semantic operations")
    lines.append("")
    lines.append("| Operation | Phase | Physical queries | Configuration dependencies |")
    lines.append("|-----------|-------|------------------|----------------------------|")
    for operation in operations:
        query_ids = operation.get("workflow_query_ids") or []
        config_fields = operation.get("workflow_config_dependency_ids") or []
        lines.append(
            f"| **{cell(operation.get('workflow_label'))}** — "
            f"{cell(operation.get('workflow_description'))} "
            f"| `{operation.get('workflow_phase_id')}` "
            f"| {', '.join(f'`{query_id}`' for query_id in query_ids) or '—'} "
            f"| {', '.join(f'`{field}`' for field in config_fields) or '—'} |"
        )
    lines.append("")

    # Options consumed outside semantic computation are derived from the
    # contract instead of maintained as a second topology list.
    option_slots = contract["classes"]["BrowserProcessingOptions"]["slots"]
    bound = {
        dependency
        for operation in operations
        for dependency in operation.get("workflow_config_dependency_ids") or []
    }
    unbound = [opt for opt in option_slots if opt not in bound]
    if unbound:
        lines.append(
            "**Output / runtime options consumed outside the DAG:** "
            + ", ".join(f"`{opt}`" for opt in unbound)
            + "."
        )
        lines.append("")

    return lines


def render_parameters(contract: dict[str, Any]) -> list[str]:
    default_range = contract.get("default_range", "string")
    slots = contract.get("slots", {})
    option_keys = contract["classes"]["BrowserProcessingOptions"]["slots"]

    lines = ["## 4. Processing parameters", ""]
    lines.append(
        f"The preprocessing contract exposes {len(option_keys)} options"
        " (`BrowserProcessingOptions`). Each is listed below with its type, default,"
        " and researcher-facing description, quoted from the contract."
    )
    lines.append("")
    lines.append("| Option | Type | Default | Description |")
    lines.append("|--------|------|---------|-------------|")
    for key in option_keys:
        slot = slots.get(key, {})
        lines.append(
            f"| `{key}` "
            f"| {render_type(slot, default_range)} "
            f"| {render_default(slot)} "
            f"| {cell(slot.get('description'))} |"
        )
    lines.append("")

    enums = contract.get("enums", {})
    if enums:
        lines.append("### 4.1 Contract enumerations")
        lines.append("")
        lines.append(
            "Options whose type is one of the enumerations below accept only these"
            " values."
        )
        lines.append("")
        for enum_name in sorted(enums):
            enum = enums[enum_name]
            desc = clean_text(enum.get("description"))
            head = f"**`{enum_name}`**"
            if desc:
                head += f" — {desc}"
            lines.append(head)
            lines.append("")
            values = enum.get("permissible_values") or {}
            for value in values:
                body = values[value] or {}
                vdesc = clean_text(body.get("description"))
                lines.append(f"- `{value}`" + (f" — {vdesc}" if vdesc else ""))
            lines.append("")
    return lines


def render_raw_input(contract: dict[str, Any]) -> list[str]:
    raw = contract["classes"]["RawChronicleEventRecord"]
    slots = contract.get("slots", {})
    lines = ["## 5. Raw-input contract", ""]
    lines.append(clean_text(raw.get("description")))
    lines.append("")
    lines.append(
        "Columns are the literal raw Chronicle CSV headers. *Required* columns are an"
        " advisory presence expectation — a missing header warns, never blocks."
    )
    lines.append("")
    lines.append("| Column | Required | Description |")
    lines.append("|--------|----------|-------------|")
    for name in raw["slots"]:
        slot = slots.get(name, {})
        required = "yes" if slot.get("required") else "optional"
        lines.append(f"| `{name}` | {required} | {cell(slot.get('description'))} |")
    lines.append("")
    return lines


def render_provenance(ontology: dict[str, Any]) -> list[str]:
    classes = ontology.get("classes", {})
    lines = ["## 6. Provenance model", ""]
    lines.append(
        "Every derived measure carries its lineage. The provenance backbone is"
        " grounded in PROV-O and P-Plan: a `WorkflowPlan` composed of"
        " `OperationDefinition`s is realized at run time by `OperationExecution` activities,"
        " each citing the content-addressed `ParameterSet` that configured it. The"
        " classes below carry the PROV-O / P-Plan / SOSA alignments that make this"
        " lineage machine-checkable."
    )
    lines.append("")
    lines.append("| Class | Aligned with | Role |")
    lines.append("|-------|--------------|------|")
    anchors = {"prov:Activity", "prov:Plan", "pplan:Plan", "pplan:Step", "sosa:Procedure"}
    provenance_by_name = {"ParameterSet", "ParameterBinding"}
    for name, cls in classes.items():
        mappings = cls.get("broad_mappings") or []
        is_provenance = name in provenance_by_name or any(m in anchors for m in mappings)
        if not is_provenance:
            continue
        aligned = ", ".join(f"`{m}`" for m in mappings) or "—"
        lines.append(f"| `{name}` | {aligned} | {cell(cls.get('description'))} |")
    lines.append("")
    lines.append(
        "At run time these classes are emitted as a JSON-LD provenance **sidecar** —"
        " a lineage ledger of `OperationExecution`s, their `ParameterSet`, and the"
        " `OperationDefinition`s they realized — which is validated against the ontology's"
        " SHACL shapes so the runtime lineage always conforms to the model above."
    )
    lines.append("")
    return lines


def render_external_mappings(ontology: dict[str, Any]) -> list[str]:
    lines = ["## 7. External framework alignment", ""]

    # Prefix / vocabulary table (skip the schema-local + tooling prefixes).
    skip_prefixes = {"linkml", "chron"}
    prefixes = ontology.get("prefixes", {})
    external = {p: ns for p, ns in prefixes.items() if p not in skip_prefixes}
    if external:
        lines.append("### 7.1 Backbone vocabularies")
        lines.append("")
        lines.append("| Prefix | Namespace |")
        lines.append("|--------|-----------|")
        for prefix in sorted(external):
            lines.append(f"| `{prefix}` | {external[prefix]} |")
        lines.append("")

    # Element → mapping table (classes, enum members, slots).
    rows: list[tuple[str, str, str]] = []
    for name, cls in ontology.get("classes", {}).items():
        for key in CLASS_MAPPING_KEYS:
            for target in cls.get(key) or []:
                rows.append((f"class `{name}`", key.replace("_mappings", "Match"), target))
    for enum_name, enum in ontology.get("enums", {}).items():
        for value, body in (enum.get("permissible_values") or {}).items():
            body = body or {}
            for key in CLASS_MAPPING_KEYS:
                for target in body.get(key) or []:
                    rows.append(
                        (f"`{enum_name}.{value}`", key.replace("_mappings", "Match"), target)
                    )
    for slot_name, slot in ontology.get("slots", {}).items():
        slot = slot or {}
        if slot.get("slot_uri"):
            rows.append((f"slot `{slot_name}`", "slot_uri", slot["slot_uri"]))

    if rows:
        lines.append("### 7.2 Term-level mappings")
        lines.append("")
        lines.append("| Ontology element | Relation | External term |")
        lines.append("|------------------|----------|---------------|")
        for element, relation, target in sorted(rows):
            lines.append(f"| {element} | `{relation}` | `{target}` |")
        lines.append("")

    see_also = ontology.get("see_also") or []
    if see_also:
        lines.append("### 7.3 Referenced frameworks")
        lines.append("")
        for ref in see_also:
            lines.append(f"- {ref}")
        lines.append("")

    comments = ontology.get("comments") or []
    if comments:
        for comment in comments:
            lines.append(f"> {clean_text(comment)}")
            lines.append("")
    return lines


# --------------------------------------------------------------------------- #
# main
# --------------------------------------------------------------------------- #
def build_document() -> str:
    ontology = load(ONTOLOGY_YAML)
    contract = load(CONTRACT_YAML)
    graph = load(GRAPH_YAML)

    blocks: list[list[str]] = [
        render_header(ontology),
        render_overview(ontology),
        render_entity_model(ontology),
        render_pipeline(contract, graph),
        render_parameters(contract),
        render_raw_input(contract),
        render_provenance(ontology),
        render_external_mappings(ontology),
    ]
    lines: list[str] = []
    for block in blocks:
        lines.extend(block)
    # Collapse to exactly one trailing newline.
    text = "\n".join(lines).rstrip("\n") + "\n"
    return text


def main(argv: list[str]) -> int:
    if len(argv) != 2:
        print("usage: generate_methods_doc.py <output.md>", file=sys.stderr)
        return 2
    output_path = Path(argv[1])
    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text(build_document(), encoding="utf-8")
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv))
