// This file is generated by web/scripts/generate_contract_artifacts.mts.
// Do not edit by hand; update the LinkML contract instead.

export const TIMEZONE_HANDLING_VALUES = [
  "selected-filter",
  "selected-convert",
  "primary-filter",
  "primary-convert",
] as const;

export const OUTPUT_KIND_VALUES = [
  "app",
  "screen",
  "plot",
  "aggregate",
  "parquet",
  "spss",
  "lineage",
] as const;

export const AGGREGATE_SHAPE_VALUES = [
  "wide",
  "long",
] as const;

export const BROWSER_PROCESSING_OPTION_KEYS = [
  "studyName",
  "processAppUsage",
  "processScreenUsage",
  "allowStopEventReuse",
  "useActivityStoppedAsFallback",
  "applyThresholdToFallback",
  "longDurationThresholdHours",
  "correctDuplicateEventTimestamps",
  "deduplicateExactRows",
  "selectedTimezone",
  "timezoneHandling",
  "useFilterFile",
  "useAppsForcingScreenOpenFile",
  "useBackgroundAppsFile",
  "useAppCodebook",
  "includeCategoryColumn",
  "enablePlotting",
  "includeFilteredAppUsageInPlots",
  "enableActivityHeatmap",
  "exportPlotsAsSvg",
  "enableAggregates",
  "aggregateShape",
  "enableParquetExport",
  "enableSpssExport",
  "enableInteractiveTimeline",
  "minimumUsageDuration",
  "filterZeroDurationSessions",
  "customAppEngagementDuration",
  "longUsageDurationThresholds",
  "longDataTimeGapThresholds",
  "screenUsageAutoLockTimeoutSeconds",
  "screenUsageAutoLockToleranceSeconds",
  "screenUsageManualLockMaxTailGapSeconds",
  "screenUsageKeyguardNearStopSeconds",
  "parallelProcessing",
  "parallelMaxWorkers",
  "sameAppInteractionTypesToStopUsageAt",
  "otherInteractionTypesToStopUsageAt",
  "modelConcurrentUsage",
  "applyMinimumUsageDurationToConcurrentSubintervals",
  "interactionTypesToRemove",
  "interactionTypeRemap",
  "proximityIntervalSeconds",
  "addNoActivityPlaceholderDays",
  "enableScreenGatedCrediting",
  "creditedSessionCapMinutes",
  "deviceLivenessGapToleranceMinutes",
  "autoLockBridgeSeconds",
  "noWitnessMinDayApps",
  "enableStudyWindowFilter",
  "enablePersonAttribution",
  "enableComplianceScoring",
  "complianceThresholdPercent",
  "enableDayCoverage",
] as const;

export const BROWSER_REQUIRED_PROCESSING_OPTION_KEYS = [
  "studyName",
  "processAppUsage",
  "processScreenUsage",
  "allowStopEventReuse",
  "useActivityStoppedAsFallback",
  "applyThresholdToFallback",
  "longDurationThresholdHours",
  "correctDuplicateEventTimestamps",
  "deduplicateExactRows",
  "timezoneHandling",
  "useFilterFile",
  "useAppsForcingScreenOpenFile",
  "useBackgroundAppsFile",
  "useAppCodebook",
  "includeCategoryColumn",
  "enablePlotting",
  "includeFilteredAppUsageInPlots",
  "enableActivityHeatmap",
  "exportPlotsAsSvg",
  "enableAggregates",
  "aggregateShape",
  "enableParquetExport",
  "enableSpssExport",
  "enableInteractiveTimeline",
  "minimumUsageDuration",
  "filterZeroDurationSessions",
  "customAppEngagementDuration",
  "longUsageDurationThresholds",
  "longDataTimeGapThresholds",
  "screenUsageAutoLockTimeoutSeconds",
  "screenUsageAutoLockToleranceSeconds",
  "screenUsageManualLockMaxTailGapSeconds",
  "screenUsageKeyguardNearStopSeconds",
  "parallelProcessing",
  "sameAppInteractionTypesToStopUsageAt",
  "otherInteractionTypesToStopUsageAt",
  "modelConcurrentUsage",
  "applyMinimumUsageDurationToConcurrentSubintervals",
  "interactionTypesToRemove",
  "interactionTypeRemap",
  "proximityIntervalSeconds",
  "addNoActivityPlaceholderDays",
  "enableScreenGatedCrediting",
  "creditedSessionCapMinutes",
  "deviceLivenessGapToleranceMinutes",
  "autoLockBridgeSeconds",
  "noWitnessMinDayApps",
  "enableStudyWindowFilter",
  "enablePersonAttribution",
  "enableComplianceScoring",
  "complianceThresholdPercent",
  "enableDayCoverage",
] as const;

export const BROWSER_SUPPORT_FILE_KEYS = [
  "filterFile",
  "appsForcingScreenOpenFile",
  "backgroundAppsFile",
  "appCodebookFile",
  "studyDatesFile",
  "deviceSharingFile",
  "surveyAttributionFile",
  "enrolledDevicesFile",
] as const;

export const BROWSER_RUNTIME_KEYS = [
  "datetimeOfPreprocessing",
] as const;

// Literal raw Chronicle CSV column headers (RawChronicleEventRecord slots).
export const RAW_CHRONICLE_COLUMNS = [
  "study_id",
  "participant_id",
  "possible_device_model",
  "username",
  "application_label",
  "interaction_type",
  "app_package_name",
  "event_timestamp",
  "start_timestamp",
  "stop_timestamp",
  "timezone",
] as const;

// Advisory presence expectation: fileInspection WARNS (never blocks) when one
// of these headers is missing — desktop-parity ingest tolerance is unchanged.
export const REQUIRED_RAW_COLUMNS = [
  "study_id",
  "participant_id",
  "application_label",
  "interaction_type",
  "app_package_name",
  "event_timestamp",
  "timezone",
] as const;

export type BrowserTimezoneHandling = (typeof TIMEZONE_HANDLING_VALUES)[number];
export type OutputKind = (typeof OUTPUT_KIND_VALUES)[number];
export type AggregateShape = (typeof AGGREGATE_SHAPE_VALUES)[number];

export type BrowserProcessingOptions = {
  studyName: string;
  processAppUsage: boolean;
  processScreenUsage: boolean;
  allowStopEventReuse: boolean;
  useActivityStoppedAsFallback: boolean;
  applyThresholdToFallback: boolean;
  longDurationThresholdHours: number;
  correctDuplicateEventTimestamps: boolean;
  deduplicateExactRows: boolean;
  selectedTimezone?: string;
  timezoneHandling: BrowserTimezoneHandling;
  useFilterFile: boolean;
  useAppsForcingScreenOpenFile: boolean;
  useBackgroundAppsFile: boolean;
  useAppCodebook: boolean;
  includeCategoryColumn: boolean;
  enablePlotting: boolean;
  includeFilteredAppUsageInPlots: boolean;
  enableActivityHeatmap: boolean;
  exportPlotsAsSvg: boolean;
  enableAggregates: boolean;
  aggregateShape: AggregateShape;
  enableParquetExport: boolean;
  enableSpssExport: boolean;
  enableInteractiveTimeline: boolean;
  minimumUsageDuration: number;
  filterZeroDurationSessions: boolean;
  customAppEngagementDuration: number;
  longUsageDurationThresholds: number[];
  longDataTimeGapThresholds: number[];
  screenUsageAutoLockTimeoutSeconds: number;
  screenUsageAutoLockToleranceSeconds: number;
  screenUsageManualLockMaxTailGapSeconds: number;
  screenUsageKeyguardNearStopSeconds: number;
  parallelProcessing: boolean;
  parallelMaxWorkers?: number;
  sameAppInteractionTypesToStopUsageAt: string[];
  otherInteractionTypesToStopUsageAt: string[];
  modelConcurrentUsage: boolean;
  applyMinimumUsageDurationToConcurrentSubintervals: boolean;
  interactionTypesToRemove: string[];
  interactionTypeRemap: string[];
  proximityIntervalSeconds: number;
  addNoActivityPlaceholderDays: boolean;
  enableScreenGatedCrediting: boolean;
  creditedSessionCapMinutes: number;
  deviceLivenessGapToleranceMinutes: number;
  autoLockBridgeSeconds: number;
  noWitnessMinDayApps: number;
  enableStudyWindowFilter: boolean;
  enablePersonAttribution: boolean;
  enableComplianceScoring: boolean;
  complianceThresholdPercent: number;
  enableDayCoverage: boolean;
};

// Key arrays by sanitization type — used by settingsPersistence to stay in sync with the schema.
export const BOOLEAN_BROWSER_OPTION_KEYS = [
  "processAppUsage",
  "processScreenUsage",
  "allowStopEventReuse",
  "useActivityStoppedAsFallback",
  "applyThresholdToFallback",
  "correctDuplicateEventTimestamps",
  "deduplicateExactRows",
  "useFilterFile",
  "useAppsForcingScreenOpenFile",
  "useBackgroundAppsFile",
  "useAppCodebook",
  "includeCategoryColumn",
  "enablePlotting",
  "includeFilteredAppUsageInPlots",
  "enableActivityHeatmap",
  "exportPlotsAsSvg",
  "enableAggregates",
  "enableParquetExport",
  "enableSpssExport",
  "enableInteractiveTimeline",
  "filterZeroDurationSessions",
  "parallelProcessing",
  "modelConcurrentUsage",
  "applyMinimumUsageDurationToConcurrentSubintervals",
  "addNoActivityPlaceholderDays",
  "enableScreenGatedCrediting",
  "enableStudyWindowFilter",
  "enablePersonAttribution",
  "enableComplianceScoring",
  "enableDayCoverage",
] as const;
export const NUMBER_BROWSER_OPTION_KEYS = [
  "longDurationThresholdHours",
  "minimumUsageDuration",
  "customAppEngagementDuration",
  "screenUsageAutoLockTimeoutSeconds",
  "screenUsageAutoLockToleranceSeconds",
  "screenUsageManualLockMaxTailGapSeconds",
  "screenUsageKeyguardNearStopSeconds",
  "proximityIntervalSeconds",
  "creditedSessionCapMinutes",
  "deviceLivenessGapToleranceMinutes",
  "autoLockBridgeSeconds",
  "noWitnessMinDayApps",
  "complianceThresholdPercent",
] as const;
export const NUMBER_ARRAY_BROWSER_OPTION_KEYS = [
  "longUsageDurationThresholds",
  "longDataTimeGapThresholds",
] as const;
export const STRING_BROWSER_OPTION_KEYS = [
  "studyName",
  "selectedTimezone",
  "timezoneHandling",
  "aggregateShape",
] as const;
export const STRING_ARRAY_BROWSER_OPTION_KEYS = [
  "sameAppInteractionTypesToStopUsageAt",
  "otherInteractionTypesToStopUsageAt",
  "interactionTypesToRemove",
  "interactionTypeRemap",
] as const;

export const DEFAULT_BROWSER_OPTIONS: BrowserProcessingOptions = {
  studyName: "",
  processAppUsage: true,
  processScreenUsage: true,
  allowStopEventReuse: false,
  useActivityStoppedAsFallback: true,
  applyThresholdToFallback: true,
  longDurationThresholdHours: 12,
  correctDuplicateEventTimestamps: true,
  deduplicateExactRows: true,
  selectedTimezone: "",
  timezoneHandling: "selected-filter",
  useFilterFile: false,
  useAppsForcingScreenOpenFile: false,
  useBackgroundAppsFile: false,
  useAppCodebook: true,
  includeCategoryColumn: false,
  enablePlotting: true,
  includeFilteredAppUsageInPlots: false,
  enableActivityHeatmap: true,
  exportPlotsAsSvg: false,
  enableAggregates: false,
  aggregateShape: "wide",
  enableParquetExport: false,
  enableSpssExport: false,
  enableInteractiveTimeline: false,
  minimumUsageDuration: 60,
  filterZeroDurationSessions: false,
  customAppEngagementDuration: 300,
  longUsageDurationThresholds: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
  longDataTimeGapThresholds: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
  screenUsageAutoLockTimeoutSeconds: 120,
  screenUsageAutoLockToleranceSeconds: 30,
  screenUsageManualLockMaxTailGapSeconds: 30,
  screenUsageKeyguardNearStopSeconds: 2,
  parallelProcessing: true,
  parallelMaxWorkers: undefined,
  sameAppInteractionTypesToStopUsageAt: ["Activity Paused", "Activity Resumed"],
  otherInteractionTypesToStopUsageAt: ["Activity Resumed", "Filtered App Resumed", "Filtered App Usage", "Filtered App Background Usage", "End of Usage Missing", "Device Shutdown"],
  modelConcurrentUsage: false,
  applyMinimumUsageDurationToConcurrentSubintervals: false,
  interactionTypesToRemove: [],
  interactionTypeRemap: [],
  proximityIntervalSeconds: 2,
  addNoActivityPlaceholderDays: false,
  enableScreenGatedCrediting: false,
  creditedSessionCapMinutes: 360,
  deviceLivenessGapToleranceMinutes: 120,
  autoLockBridgeSeconds: 120,
  noWitnessMinDayApps: 2,
  enableStudyWindowFilter: false,
  enablePersonAttribution: false,
  enableComplianceScoring: false,
  complianceThresholdPercent: 70,
  enableDayCoverage: false,
};

export const BROWSER_OPTION_TOOLTIPS = {
  studyName: {
    title: "Study name",
    body: "Your label for this study. Written into the `study_name` column of every output row. This is your own naming, not the `study_id` column from the raw data — that is preserved unchanged.",
  },
  processAppUsage: {
    title: "App usage output",
    body: "Run the app-usage algorithm and include the app-usage CSV in the output ZIP. Each session spans from an Activity Resumed to its matching stop event.",
  },
  processScreenUsage: {
    title: "Screen usage output",
    body: "Derive screen-usage sessions and include the screen-usage CSV in the output ZIP. Sessions are inferred from Screen Interactive / Screen Non-Interactive events.",
  },
  allowStopEventReuse: {
    title: "Allow stop-event reuse",
    body: "Lets a single stop event close multiple overlapping sessions. Off by default — stop events are consumed once.",
  },
  useActivityStoppedAsFallback: {
    title: "Use Activity Stopped fallback",
    body: "If a session has no explicit stop, fall back to the next Activity Stopped event for the same app. Helps with noisy traces.",
  },
  applyThresholdToFallback: {
    title: "Apply threshold to fallback",
    body: "When the fallback path is used and the implied session is longer than the max threshold above, treat it as a missing-end-of-usage instead of a real session.",
  },
  longDurationThresholdHours: {
    title: "Max session duration threshold",
    body: "Sessions longer than this many hours are flagged as suspiciously long, which may indicate an instrumentation gap rather than real use.",
    example: "default 12 hours",
  },
  correctDuplicateEventTimestamps: {
    title: "Correct duplicate timestamps",
    body: "When two events share the same timestamp, nudge the second one forward by microseconds so ordering is preserved deterministically.",
  },
  deduplicateExactRows: {
    title: "Collapse exact-duplicate rows",
    body: "Drop fully-identical raw events (same participant, timestamp, app, and interaction type) before processing. Re-exported Chronicle data often repeats rows verbatim; the first occurrence is kept. Turn this off to keep every raw row as-is.",
  },
  selectedTimezone: {
    title: "Selected timezone",
    body: "Pick from the typical IANA names (e.g. America/Chicago). When discovery runs, found timezones from your file are added to the suggestions.",
  },
  timezoneHandling: {
    title: "Timezone handling",
    body: "Decides what happens to rows with timezones that differ from the selected one — keep only the matching rows, convert mixed rows to a common zone, or anchor on the file's primary zone.",
  },
  useFilterFile: {
    title: "Use filter file",
    body: "If on, the pipeline labels apps in your filter list as filtered (instead of dropping them). Without an uploaded file the app falls back to the bundled default. Off by default: this is an app-policy (cleaning) decision, not part of standard preprocessing — enable it only when your study's protocol says to.",
  },
  useAppsForcingScreenOpenFile: {
    title: "Use apps-forcing-screen-open file",
    body: "Apps in this list are treated as ones that force the screen to stay on during screen-usage derivation, which influences how locks/unlocks are interpreted.",
  },
  useBackgroundAppsFile: {
    title: "Use background-apps file",
    body: "Apps in this list (e.g. music, navigation) keep running after they are backgrounded. Their app-usage session is not closed when they are paused or when another app comes to the foreground; it stays alive until that app's own Activity Stopped. The resulting overlap with the foreground app is resolved into primary/secondary layers (the concurrent-usage split is applied automatically when this is on). Without an uploaded file the bundled default is used.",
  },
  useAppCodebook: {
    title: "Use app codebook",
    body: "Enriches each output row with category metadata from the codebook (Play Store genre, USC category, UMich classifications, etc.). Without an uploaded codebook the bundled default is used.",
  },
  includeCategoryColumn: {
    title: "Include app category column",
    body: "Add the normalized broad app category (the same value used to colour the plots — Games, Education, Social & Communication, …) as a `broad_app_category` column in the app-usage output. Derived by coalescing the codebook's per-source category columns and mapping them onto the standard palette. Requires the app codebook; off by default.",
  },
  enablePlotting: {
    title: "Generate app-usage plots",
    body: "After preprocessing, renders one horizontal-bar timeline chart per participant and includes the PNGs in the output ZIP. Each bar is coloured by app category.",
  },
  includeFilteredAppUsageInPlots: {
    title: "Include filtered apps in plots",
    body: "When on, bars for apps that were filtered (but retained in the output) are drawn alongside normal app-usage bars.",
  },
  enableActivityHeatmap: {
    title: "Generate activity heatmaps",
    body: "Alongside the timeline chart, render an hour-of-day × calendar-day heatmap PNG per participant showing when app usage happened. Only applies when plot generation is on. Turn off to keep just the timeline charts (one fewer PNG per participant).",
  },
  exportPlotsAsSvg: {
    title: "Also export plots as SVG (vector)",
    body: "In addition to the PNG charts, write a scalable vector SVG of each plot (timeline, and heatmap when enabled) into the output ZIP. SVGs stay sharp at any zoom and are editable in vector tools. Off by default to avoid adding a second file per plot. Only applies when plot generation is on.",
  },
  enableAggregates: {
    title: "Aggregate summaries",
    body: "Emit extra summary CSVs alongside the per-session output: a daily and weekly summary (screen/app time, session counts, app switches, pickups, mean & longest session, first/last use), a per-app breakdown, a per-category time budget (when a codebook is loaded), and an app co-usage matrix (when concurrent usage is modeled). Off by default.",
  },
  aggregateShape: {
    title: "Aggregate layout",
    body: "Layout for the daily/weekly summaries — \"wide\" (one row per period, metrics as columns) or \"long\" (tidy: one row per period per metric). The per-app, category, and co-usage outputs are always long.",
  },
  enableParquetExport: {
    title: "Also export Parquet",
    body: "In addition to the CSV outputs, write each app-usage and screen-usage table as an Apache Parquet file (typed columns, smaller and far faster to load in R/Python via arrow/polars/pandas). Same rows and columns as the CSV, with native dtypes preserved (timestamps stay as formatted strings). Off by default.",
  },
  enableSpssExport: {
    title: "Also export SPSS (.sav)",
    body: "In addition to the CSV outputs, write each app-usage and screen-usage table as an SPSS/PSPP system file (.sav) with typed variables and the column names as variable labels — open it directly in SPSS or PSPP. Same rows and columns as the CSV. Off by default. (Stata .dta is not yet supported.)",
  },
  enableInteractiveTimeline: {
    title: "Interactive timeline explorer",
    body: "Show an in-browser zoomable/pannable timeline of every session (app and screen), coloured by app category, with hover details — rendered live in the results panel from a compact per-session payload. This payload is only produced when the option is on, to avoid bloating results for large cohorts. Off by default.",
  },
  minimumUsageDuration: {
    title: "Minimum usage duration (seconds)",
    body: "Sessions shorter than this threshold have their duration_seconds and duration_minutes set to null in the output. The session row is retained. Set to 0 to disable. The 60-second default nulls sub-minute foreground blips (UI transitions and glances), matching the studies' locked preprocessing configuration.",
    example: "default 60 seconds",
  },
  filterZeroDurationSessions: {
    title: "Filter zero-duration sessions",
    body: "Removes app-usage session rows whose computed duration is exactly zero or negative. These arise from duplicate events at the same millisecond, common on Fire tablets.",
  },
  customAppEngagementDuration: {
    title: "Custom app engagement duration",
    body: "Window in seconds within which two consecutive activities on the same app count as continued engagement. Affects how first new engagement is detected.",
    example: "default 300 seconds",
  },
  longUsageDurationThresholds: {
    title: "Long-usage thresholds (hours)",
    body: "Comma-separated hour values. For each value the pipeline emits a column flagging sessions whose duration exceeds it.",
    example: "default 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12",
  },
  longDataTimeGapThresholds: {
    title: "Long data-gap thresholds (hours)",
    body: "Comma-separated hour values. For each value the pipeline emits a column flagging time gaps between events that exceed it.",
    example: "default 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12",
  },
  screenUsageAutoLockTimeoutSeconds: {
    title: "Auto-lock timeout (seconds)",
    body: "Idle period after which the screen is assumed to have auto-locked. Used to infer screen-off time when an explicit lock is missing.",
    example: "default 120 seconds",
  },
  screenUsageAutoLockToleranceSeconds: {
    title: "Auto-lock tolerance (seconds)",
    body: "Slack window around the auto-lock timeout to absorb small clock skews when classifying lock events.",
    example: "default 30 seconds",
  },
  screenUsageManualLockMaxTailGapSeconds: {
    title: "Manual-lock max tail gap (seconds)",
    body: "Maximum allowed gap between the last meaningful activity and an explicit lock event for the lock to count as manual.",
    example: "default 30 seconds",
  },
  screenUsageKeyguardNearStopSeconds: {
    title: "Keyguard-near-stop window (seconds)",
    body: "If the keyguard appears within this many seconds of a session stop, treat it as part of the same lock event.",
    example: "default 2 seconds",
  },
  parallelProcessing: {
    title: "Enable parallel file processing",
    body: "When this is on, the app can process more than one uploaded raw file at the same time. It usually helps only when you upload multiple files; one file still runs by itself.",
  },
  parallelMaxWorkers: {
    title: "Max parallel workers",
    body: "The maximum number of files the app may process at the same time. Use 0 to let the app choose a safe number based on file sizes and browser capacity. Lower it if the browser becomes slow or memory-heavy.",
  },
  sameAppInteractionTypesToStopUsageAt: {
    title: "Same-app stop types",
    body: "Interaction types that, when seen for the same app as the current session, end that session.",
  },
  otherInteractionTypesToStopUsageAt: {
    title: "Other-app stop types",
    body: "Interaction types from any other source that close the current session — e.g. a different app coming to the foreground or the device shutting down. \"End of Usage Missing\" is an unmatched foreground/resume (the app came to the foreground; only its close was never seen), so it also displaces whatever was foreground and must interrupt other app usage — without it an unmatched filtered foreground silently stopped interrupting valid sessions only when the filter was on (the two-pass interrupt leak).",
  },
  modelConcurrentUsage: {
    title: "Model concurrent (Picture-in-Picture) usage",
    body: "When enabled, an app session runs to its own stop event instead of ending when another app is foregrounded. Overlapping sessions are split into a primary (sole-foreground) layer and a secondary (running-underneath / PiP) layer, reported via the usage_layer column. Default off; output is unchanged when off.",
  },
  applyMinimumUsageDurationToConcurrentSubintervals: {
    title: "Apply minimum usage duration to concurrent sub-intervals",
    body: "Only relevant when model_concurrent_usage is on. When enabled, a split primary/secondary sub-interval shorter than minimum_usage_duration has its duration_seconds/duration_minutes nulled (the row is kept). Off by default, so sub-interval durations are always populated, matching every surface.",
  },
  interactionTypesToRemove: {
    title: "Interaction types to remove",
    body: "Rows of these types are dropped from the final output. Useful for stripping noisy events you don't want surfaced in the CSV.",
  },
  interactionTypeRemap: {
    title: "Custom interaction-type mappings",
    body: "Map vendor-specific raw interaction_type strings onto the canonical names the pipeline understands (e.g. Activity Resumed / Activity Paused / Activity Stopped), for non-standard Chronicle exports. Each entry is \"Raw value => Canonical name\". Applied before the built-in mapping, so it also overrides built-ins. Default empty.",
  },
  proximityIntervalSeconds: {
    title: "Intra-app teardown grace (seconds)",
    body: "When greater than 0, an Activity Stopped fallback close landing within this many seconds of a re-resumed session's start is treated as an intra-app teardown artifact (the app was torn down then immediately re-resumed) rather than a real close, so the session stays open for the next genuine stop event. Set to 0 to disable. When on, app-usage matching runs in a JavaScript matcher path (the shared WASM matcher has no proximity parameter); with it off the output is byte-identical to before. The 2-second default matches the studies' locked preprocessing configuration.",
    example: "default 2 seconds",
  },
  addNoActivityPlaceholderDays: {
    title: "Add no-activity placeholder days",
    body: "For each participant, any calendar day that has raw event data but produces no app-usage sessions gets one zero-duration placeholder row (com.placeholder.noactivity) so day-level summaries can distinguish a genuine no-use day from a day with no data at all. The window is derived from the participant's own data (first to last day with raw events). Default off.",
  },
  enableScreenGatedCrediting: {
    title: "Screen-gated usage credit",
    body: "Emit an additional, side-by-side \"Credited App Usage\" CSV in which each app session is reduced to the intervals where the screen was witnessed ON and the device was demonstrably alive (event cadence within the liveness tolerance), truncated at the credited-session cap. The headline app-usage output is never changed by this option. Long held-open sessions are credited only while the device was actually lit and alive. Off by default.",
  },
  creditedSessionCapMinutes: {
    title: "Credited-session cap (minutes)",
    body: "Upper bound on any single credited session interval. Credit is truncated at this many minutes from the session start (never zeroed out).",
    example: "default 360 minutes (6 hours)",
  },
  deviceLivenessGapToleranceMinutes: {
    title: "Device-liveness gap tolerance (minutes)",
    body: "An event silence shorter than this keeps the device \"alive\" for crediting; a longer silence breaks the chain. A Device Startup landing inside a silence always breaks it (a boot proves the device was off).",
    example: "default 120 minutes",
  },
  autoLockBridgeSeconds: {
    title: "Auto-lock bridge (seconds)",
    body: "A screen-OFF blip shorter than this cannot be the device auto-lock, so credit bridges across it (screen bounce, not a real lock).",
    example: "default 120 seconds",
  },
  noWitnessMinDayApps: {
    title: "No-witness fallback: min distinct apps per day",
    body: "When a session has no screen witness at all, credit its alive time only if the participant-day switched across at least this many distinct apps (you cannot switch apps on a dark screen). Below the floor, the session earns no credit.",
    example: "default 2",
  },
  enableStudyWindowFilter: {
    title: "Study-window filter",
    body: "Keep only sessions whose LOCAL calendar date falls inside the participant's study window from the study-dates file (inclusive). Requires the study-dates support file.",
  },
  enablePersonAttribution: {
    title: "Person attribution (shared devices)",
    body: "On shared devices, attribute each session to a person using the device-sharing table (exact participant match only) and optional usage-survey answers; usage attributed to someone other than the target becomes \"Non-Target Child App Usage\" (kept, excluded from screen time). Requires the device-sharing support file.",
  },
  enableComplianceScoring: {
    title: "Compliance scoring",
    body: "Emit a per-participant-day compliance report: known / (known + unknown) attributed minutes, with non-shared devices at 100 by definition. Days at 100 with zero real usage are kept but flagged.",
  },
  complianceThresholdPercent: {
    title: "Compliance threshold (%)",
    body: "A day counts as valid when its compliance is at or above this percent. Study-specific; the default mirrors the common 70% rule.",
    example: "default 70",
  },
  enableDayCoverage: {
    title: "Day coverage report",
    body: "Emit a per-participant-day coverage report distinguishing days with usage, \"no activity\" days (raw events but no usage), and \"no data\" days (device silent), across the study window when one is loaded. Fails loudly if any windowed day would end uncovered.",
  },
} as const;
