// This file is generated by web/scripts/generate_contract_artifacts.mts.
// Do not edit by hand; update the LinkML contract instead.

export const TIMEZONE_HANDLING_VALUES = [
  "selected-filter",
  "selected-convert",
  "primary-filter",
  "primary-convert",
] as const;

export const OUTPUT_KIND_VALUES = [
  "app",
  "screen",
  "plot",
] as const;

export const BROWSER_PROCESSING_OPTION_KEYS = [
  "studyName",
  "processAppUsage",
  "processScreenUsage",
  "allowStopEventReuse",
  "useActivityStoppedAsFallback",
  "applyThresholdToFallback",
  "longDurationThresholdHours",
  "correctDuplicateEventTimestamps",
  "selectedTimezone",
  "timezoneHandling",
  "useFilterFile",
  "useAppsForcingScreenOpenFile",
  "useAppCodebook",
  "enablePlotting",
  "includeFilteredAppUsageInPlots",
  "minimumUsageDuration",
  "filterZeroDurationSessions",
  "customAppEngagementDuration",
  "longUsageDurationThresholds",
  "longDataTimeGapThresholds",
  "screenUsageAutoLockTimeoutSeconds",
  "screenUsageAutoLockToleranceSeconds",
  "screenUsageManualLockMaxTailGapSeconds",
  "screenUsageKeyguardNearStopSeconds",
  "parallelProcessing",
  "parallelMaxWorkers",
  "sameAppInteractionTypesToStopUsageAt",
  "otherInteractionTypesToStopUsageAt",
  "modelConcurrentUsage",
  "interactionTypesToRemove",
] as const;

export const BROWSER_REQUIRED_PROCESSING_OPTION_KEYS = [
  "studyName",
  "processAppUsage",
  "processScreenUsage",
  "allowStopEventReuse",
  "useActivityStoppedAsFallback",
  "applyThresholdToFallback",
  "longDurationThresholdHours",
  "correctDuplicateEventTimestamps",
  "timezoneHandling",
  "useFilterFile",
  "useAppsForcingScreenOpenFile",
  "useAppCodebook",
  "enablePlotting",
  "includeFilteredAppUsageInPlots",
  "minimumUsageDuration",
  "filterZeroDurationSessions",
  "customAppEngagementDuration",
  "longUsageDurationThresholds",
  "longDataTimeGapThresholds",
  "screenUsageAutoLockTimeoutSeconds",
  "screenUsageAutoLockToleranceSeconds",
  "screenUsageManualLockMaxTailGapSeconds",
  "screenUsageKeyguardNearStopSeconds",
  "parallelProcessing",
  "sameAppInteractionTypesToStopUsageAt",
  "otherInteractionTypesToStopUsageAt",
  "interactionTypesToRemove",
] as const;

export const BROWSER_SUPPORT_FILE_KEYS = [
  "filterFile",
  "appsForcingScreenOpenFile",
  "appCodebookFile",
] as const;

export const BROWSER_RUNTIME_KEYS = [
  "datetimeOfPreprocessing",
] as const;

export type BrowserTimezoneHandling = (typeof TIMEZONE_HANDLING_VALUES)[number];
export type OutputKind = (typeof OUTPUT_KIND_VALUES)[number];

export type BrowserProcessingOptions = {
  studyName: string;
  processAppUsage: boolean;
  processScreenUsage: boolean;
  allowStopEventReuse: boolean;
  useActivityStoppedAsFallback: boolean;
  applyThresholdToFallback: boolean;
  longDurationThresholdHours: number;
  correctDuplicateEventTimestamps: boolean;
  selectedTimezone?: string;
  timezoneHandling: BrowserTimezoneHandling;
  useFilterFile: boolean;
  useAppsForcingScreenOpenFile: boolean;
  useAppCodebook: boolean;
  enablePlotting: boolean;
  includeFilteredAppUsageInPlots: boolean;
  minimumUsageDuration: number;
  filterZeroDurationSessions: boolean;
  customAppEngagementDuration: number;
  longUsageDurationThresholds: number[];
  longDataTimeGapThresholds: number[];
  screenUsageAutoLockTimeoutSeconds: number;
  screenUsageAutoLockToleranceSeconds: number;
  screenUsageManualLockMaxTailGapSeconds: number;
  screenUsageKeyguardNearStopSeconds: number;
  parallelProcessing: boolean;
  parallelMaxWorkers?: number;
  sameAppInteractionTypesToStopUsageAt: string[];
  otherInteractionTypesToStopUsageAt: string[];
  modelConcurrentUsage?: boolean;
  interactionTypesToRemove: string[];
};

// Key arrays by sanitization type — used by settingsPersistence to stay in sync with the schema.
export const BOOLEAN_BROWSER_OPTION_KEYS = [
  "processAppUsage",
  "processScreenUsage",
  "allowStopEventReuse",
  "useActivityStoppedAsFallback",
  "applyThresholdToFallback",
  "correctDuplicateEventTimestamps",
  "useFilterFile",
  "useAppsForcingScreenOpenFile",
  "useAppCodebook",
  "enablePlotting",
  "includeFilteredAppUsageInPlots",
  "filterZeroDurationSessions",
  "parallelProcessing",
  "modelConcurrentUsage",
] as const;
export const NUMBER_BROWSER_OPTION_KEYS = [
  "longDurationThresholdHours",
  "minimumUsageDuration",
  "customAppEngagementDuration",
  "screenUsageAutoLockTimeoutSeconds",
  "screenUsageAutoLockToleranceSeconds",
  "screenUsageManualLockMaxTailGapSeconds",
  "screenUsageKeyguardNearStopSeconds",
] as const;
export const NUMBER_ARRAY_BROWSER_OPTION_KEYS = [
  "longUsageDurationThresholds",
  "longDataTimeGapThresholds",
] as const;
export const STRING_BROWSER_OPTION_KEYS = [
  "studyName",
  "selectedTimezone",
  "timezoneHandling",
] as const;
export const STRING_ARRAY_BROWSER_OPTION_KEYS = [
  "sameAppInteractionTypesToStopUsageAt",
  "otherInteractionTypesToStopUsageAt",
  "interactionTypesToRemove",
] as const;

export const DEFAULT_BROWSER_OPTIONS: BrowserProcessingOptions = {
  studyName: "",
  processAppUsage: true,
  processScreenUsage: false,
  allowStopEventReuse: false,
  useActivityStoppedAsFallback: true,
  applyThresholdToFallback: true,
  longDurationThresholdHours: 12,
  correctDuplicateEventTimestamps: true,
  selectedTimezone: "",
  timezoneHandling: "selected-filter",
  useFilterFile: true,
  useAppsForcingScreenOpenFile: false,
  useAppCodebook: true,
  enablePlotting: false,
  includeFilteredAppUsageInPlots: false,
  minimumUsageDuration: 0,
  filterZeroDurationSessions: false,
  customAppEngagementDuration: 300,
  longUsageDurationThresholds: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
  longDataTimeGapThresholds: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
  screenUsageAutoLockTimeoutSeconds: 120,
  screenUsageAutoLockToleranceSeconds: 30,
  screenUsageManualLockMaxTailGapSeconds: 30,
  screenUsageKeyguardNearStopSeconds: 2,
  parallelProcessing: false,
  parallelMaxWorkers: undefined,
  sameAppInteractionTypesToStopUsageAt: ["Activity Paused", "Activity Resumed"],
  otherInteractionTypesToStopUsageAt: ["Activity Resumed", "Filtered App Resumed", "Filtered App Usage", "Device Shutdown"],
  modelConcurrentUsage: undefined,
  interactionTypesToRemove: [],
};

export const BROWSER_OPTION_TOOLTIPS = {
  studyName: {
    title: "Study name",
    body: "Your label for this study. Written into the `study_name` column of every output row. This is your own naming, not the `study_id` column from the raw data — that is preserved unchanged.",
  },
  processAppUsage: {
    title: "App usage output",
    body: "Run the app-usage algorithm and include the app-usage CSV in the output ZIP. Each session spans from an Activity Resumed to its matching stop event.",
  },
  processScreenUsage: {
    title: "Screen usage output",
    body: "Derive screen-usage sessions and include the screen-usage CSV in the output ZIP. Sessions are inferred from Screen Interactive / Screen Non-Interactive events.",
  },
  allowStopEventReuse: {
    title: "Allow stop-event reuse",
    body: "Lets a single stop event close multiple overlapping sessions. Off by default — stop events are consumed once.",
  },
  useActivityStoppedAsFallback: {
    title: "Use Activity Stopped fallback",
    body: "If a session has no explicit stop, fall back to the next Activity Stopped event for the same app. Helps with noisy traces.",
  },
  applyThresholdToFallback: {
    title: "Apply threshold to fallback",
    body: "When the fallback path is used and the implied session is longer than the max threshold above, treat it as a missing-end-of-usage instead of a real session.",
  },
  longDurationThresholdHours: {
    title: "Max session duration threshold",
    body: "Sessions longer than this many hours are flagged as suspiciously long, which may indicate an instrumentation gap rather than real use.",
    example: "default 12 hours",
  },
  correctDuplicateEventTimestamps: {
    title: "Correct duplicate timestamps",
    body: "When two events share the same timestamp, nudge the second one forward by microseconds so ordering is preserved deterministically.",
  },
  selectedTimezone: {
    title: "Selected timezone",
    body: "Pick from the typical IANA names (e.g. America/Chicago). When discovery runs, found timezones from your file are added to the suggestions.",
  },
  timezoneHandling: {
    title: "Timezone handling",
    body: "Decides what happens to rows with timezones that differ from the selected one — keep only the matching rows, convert mixed rows to a common zone, or anchor on the file's primary zone.",
  },
  useFilterFile: {
    title: "Use filter file",
    body: "If on, the pipeline labels apps in your filter list as filtered (instead of dropping them). Without an uploaded file the app falls back to the bundled default.",
  },
  useAppsForcingScreenOpenFile: {
    title: "Use apps-forcing-screen-open file",
    body: "Apps in this list are treated as ones that force the screen to stay on during screen-usage derivation, which influences how locks/unlocks are interpreted.",
  },
  useAppCodebook: {
    title: "Use app codebook",
    body: "Enriches each output row with category metadata from the codebook (Play Store genre, USC category, UMich classifications, etc.). Without an uploaded codebook the bundled default is used.",
  },
  enablePlotting: {
    title: "Generate app-usage plots",
    body: "After preprocessing, renders one horizontal-bar timeline chart per participant and includes the PNGs in the output ZIP. Each bar is coloured by app category.",
  },
  includeFilteredAppUsageInPlots: {
    title: "Include filtered apps in plots",
    body: "When on, bars for apps that were filtered (but retained in the output) are drawn alongside normal app-usage bars.",
  },
  minimumUsageDuration: {
    title: "Minimum usage duration (seconds)",
    body: "Sessions shorter than this threshold have their duration_seconds and duration_minutes set to null in the output. The session row is retained. Set to 0 to disable.",
    example: "default 0 (disabled)",
  },
  filterZeroDurationSessions: {
    title: "Filter zero-duration sessions",
    body: "Removes app-usage session rows whose computed duration is exactly zero or negative. These arise from duplicate events at the same millisecond, common on Fire tablets.",
  },
  customAppEngagementDuration: {
    title: "Custom app engagement duration",
    body: "Window in seconds within which two consecutive activities on the same app count as continued engagement. Affects how first new engagement is detected.",
    example: "default 300 seconds",
  },
  longUsageDurationThresholds: {
    title: "Long-usage thresholds (hours)",
    body: "Comma-separated hour values. For each value the pipeline emits a column flagging sessions whose duration exceeds it.",
    example: "default 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12",
  },
  longDataTimeGapThresholds: {
    title: "Long data-gap thresholds (hours)",
    body: "Comma-separated hour values. For each value the pipeline emits a column flagging time gaps between events that exceed it.",
    example: "default 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12",
  },
  screenUsageAutoLockTimeoutSeconds: {
    title: "Auto-lock timeout (seconds)",
    body: "Idle period after which the screen is assumed to have auto-locked. Used to infer screen-off time when an explicit lock is missing.",
    example: "default 120 seconds",
  },
  screenUsageAutoLockToleranceSeconds: {
    title: "Auto-lock tolerance (seconds)",
    body: "Slack window around the auto-lock timeout to absorb small clock skews when classifying lock events.",
    example: "default 30 seconds",
  },
  screenUsageManualLockMaxTailGapSeconds: {
    title: "Manual-lock max tail gap (seconds)",
    body: "Maximum allowed gap between the last meaningful activity and an explicit lock event for the lock to count as manual.",
    example: "default 30 seconds",
  },
  screenUsageKeyguardNearStopSeconds: {
    title: "Keyguard-near-stop window (seconds)",
    body: "If the keyguard appears within this many seconds of a session stop, treat it as part of the same lock event.",
    example: "default 2 seconds",
  },
  parallelProcessing: {
    title: "Enable parallel file processing",
    body: "When this is on, the app can process more than one uploaded raw file at the same time. It usually helps only when you upload multiple files; one file still runs by itself.",
  },
  parallelMaxWorkers: {
    title: "Max parallel workers",
    body: "The maximum number of files the app may process at the same time. Use 0 to let the app choose a safe number based on file sizes and browser capacity. Lower it if the browser becomes slow or memory-heavy.",
  },
  sameAppInteractionTypesToStopUsageAt: {
    title: "Same-app stop types",
    body: "Interaction types that, when seen for the same app as the current session, end that session.",
  },
  otherInteractionTypesToStopUsageAt: {
    title: "Other-app stop types",
    body: "Interaction types from any other source that close the current session — e.g. a different app coming to the foreground or the device shutting down.",
  },
  modelConcurrentUsage: {
    title: "Model concurrent (Picture-in-Picture) usage",
    body: "When enabled, an app session runs to its own stop event instead of ending when another app is foregrounded. Overlapping sessions are split into a primary (sole-foreground) layer and a secondary (running-underneath / PiP) layer, reported via the usage_layer column. Default off; output is unchanged when off.",
  },
  interactionTypesToRemove: {
    title: "Interaction types to remove",
    body: "Rows of these types are dropped from the final output. Useful for stripping noisy events you don't want surfaced in the CSV.",
  },
} as const;
