// This file is generated by web/scripts/generate_contract_artifacts.mts.
// Do not edit by hand; update the LinkML contract instead.

export const USAGE_SESSION_MODE_VALUES = [
  "app_usage",
  "screen_usage",
  "app_and_screen_usage",
] as const;

export const TIMEZONE_HANDLING_VALUES = [
  "selected-filter",
  "selected-convert",
  "primary-filter",
  "primary-convert",
] as const;

export const OUTPUT_KIND_VALUES = [
  "app",
  "screen",
] as const;

export const BROWSER_PROCESSING_OPTION_KEYS = [
  "studyName",
  "usageSessionMode",
  "allowStopEventReuse",
  "useActivityStoppedAsFallback",
  "applyThresholdToFallback",
  "longDurationThresholdHours",
  "correctDuplicateEventTimestamps",
  "selectedTimezone",
  "timezoneHandling",
  "useFilterFile",
  "useKeepAwakeAppsFile",
  "useAppCodebook",
  "includeFilteredAppUsageInPlots",
  "plotOnlyTargetChildData",
  "minimumUsageDuration",
  "customAppEngagementDuration",
  "longUsageDurationThresholds",
  "longDataTimeGapThresholds",
  "screenUsageAutoLockTimeoutSeconds",
  "screenUsageAutoLockToleranceSeconds",
  "screenUsageManualLockMaxTailGapSeconds",
  "screenUsageKeyguardNearStopSeconds",
  "parallelProcessing",
  "parallelMaxWorkers",
  "sameAppInteractionTypesToStopUsageAt",
  "otherInteractionTypesToStopUsageAt",
  "interactionTypesToRemove",
] as const;

export const BROWSER_REQUIRED_PROCESSING_OPTION_KEYS = [
  "studyName",
  "usageSessionMode",
  "allowStopEventReuse",
  "useActivityStoppedAsFallback",
  "applyThresholdToFallback",
  "longDurationThresholdHours",
  "correctDuplicateEventTimestamps",
  "timezoneHandling",
  "useFilterFile",
  "useKeepAwakeAppsFile",
  "useAppCodebook",
  "includeFilteredAppUsageInPlots",
  "plotOnlyTargetChildData",
  "minimumUsageDuration",
  "customAppEngagementDuration",
  "longUsageDurationThresholds",
  "longDataTimeGapThresholds",
  "screenUsageAutoLockTimeoutSeconds",
  "screenUsageAutoLockToleranceSeconds",
  "screenUsageManualLockMaxTailGapSeconds",
  "screenUsageKeyguardNearStopSeconds",
  "parallelProcessing",
  "sameAppInteractionTypesToStopUsageAt",
  "otherInteractionTypesToStopUsageAt",
  "interactionTypesToRemove",
] as const;

export const BROWSER_SUPPORT_FILE_KEYS = [
  "filterFile",
  "keepAwakeAppsFile",
  "appCodebookFile",
] as const;

export const BROWSER_RUNTIME_KEYS = [
  "datetimeOfPreprocessing",
] as const;

export type BrowserUsageSessionMode = (typeof USAGE_SESSION_MODE_VALUES)[number];
export type BrowserTimezoneHandling = (typeof TIMEZONE_HANDLING_VALUES)[number];
export type OutputKind = (typeof OUTPUT_KIND_VALUES)[number];
