// This file is generated by
// rust/chronicle_preprocessing_runtime_wasm/examples/boundary_model.rs.
// Do not edit by hand; change the Rust serialization model and run
// `npm run generate:boundary` (verified by `npm run check:boundary`).
//
// The model below drives the STRUCTURAL half of the fail-closed WASM
// boundary decoder in rustPipelineRuntime.ts: field presence, JSON
// names, nullability, value domains, collection shapes, and enum
// spellings. Semantic cross-checks (protocol pins, certificate
// agreement, checkpoint domains, row accounting, artifact-catalog
// agreement) remain hand-written beside the decoder.
import type { BoundaryModel } from "@/lib/runtimeBoundaryModel";

export type ArtifactRef = {
  artifact_id: string;
  digest: string;
  media_type: string;
  size: number;
  derived_from: string[];
  qualifiers: Record<string, string>;
};

export type DependencyCacheDecision = {
  mode: DependencyCacheMode;
  certificate_digest: string | null;
  binding_surface_digest: string | null;
  empirical_evidence_current: boolean;
  reasons: string[];
};

export type DependencyCacheMode = "certified_narrow" | "conservative_full";

export type ExecutionStatus = "cached" | "recomputed" | "error" | "skipped" | "bypassed";

export type MaterializationState = "open" | "ready" | "satisfied" | "blocked" | "invalid" | "not_applicable";

export type OpenObligation = {
  obligation_id: string;
  role_id: string;
  query_group_id: string | null;
  state: MaterializationState;
  reason_id: string;
};

export type QualificationDecision = "accepted" | "rejected" | "ambiguous";

export type QualificationRuleEvaluation = {
  rule_id: string;
  passed: boolean;
  expected: string;
  observed: string;
};

export type QualificationTrace = {
  trace_id: string;
  candidate_id: string;
  candidate_revision: number;
  artifact_digest: string;
  qualifiers_digest: string;
  asserted_role_ids: string[];
  selected_role_id: string | null;
  decision: QualificationDecision;
  rule_evaluations: QualificationRuleEvaluation[];
  reason_id: string;
};

export type QueryGroupExecution = {
  query_group_id: string;
  capability_id: string;
  status: ExecutionStatus;
  input_key: string;
  output: ArtifactRef | null;
  reason_id: string;
};

export type ReviewRuntimeManifest = {
  protocolVersion: string;
  preprocessorVersion: string;
  requestId: string;
  command: string;
  workspaceId: string;
  previousWorkspaceRootDigest: string | null;
  inputDigest: string;
  optionsDigest: string;
  implementationDigest: string;
  buildEnvironmentDigest: string;
  planDigest: string;
  profileDigest: string;
  profileLockDigest: string;
  productContractDigest: string;
  dependencyCertificateDigest: string;
  dependencyCacheDecision: DependencyCacheDecision;
  counts: RuntimeCounts;
  availableTimezones: string[];
  timezone: string;
  timezoneAction: string;
  rowsBeforeTimezoneHandling: number;
  rowsAfterTimezoneHandling: number;
  rowsRemovedByTimezone: number;
  duplicateTimestampsCorrected: number;
  exactDuplicateRowsRemoved: number;
  queryGroupExecutions: QueryGroupExecution[];
  queryExecutions: RuntimeQueryExecution[];
  cacheSources: string[];
  reviewSummaryDigest: string;
  comparisonDigest: string;
  reviewSummaryReused: boolean;
};

export type RoleAssignment = {
  assignment_id: string;
  role_id: string;
  artifact: ArtifactRef;
  qualifiers: Record<string, string>;
  revision: number;
};

export type RoleRequirementTrace = {
  trace_id: string;
  role_id: string;
  required: boolean;
  unconditional: boolean;
  condition_id: string | null;
  condition_result: boolean | null;
  candidate_trace_ids: string[];
  accepted_assignment_ids: string[];
  state: MaterializationState;
  reason_id: string;
};

export type RuntimeArtifactMetadata = {
  artifactId: string;
  kind: string;
  mediaType: string;
  digest: string;
  size: number;
  derivedFrom: string[];
  rowCount?: number;
  previewRows?: string[][];
};

export type RuntimeCounts = {
  original: number;
  processed: number;
  app: number;
  screen: number;
};

export type RuntimeManifest = {
  protocolVersion: string;
  preprocessorVersion: string;
  requestId: string;
  command: string;
  implementation: string;
  implementationDigest: string;
  buildEnvironmentDigest: string;
  scope: string;
  planDigest: string;
  profileDigest: string;
  profileLockDigest: string;
  runtimeAuthorityDigest: string;
  productContractDigest: string;
  dependencyCertificateDigest: string;
  dependencyCacheDecision: DependencyCacheDecision;
  previousWorkspaceRootDigest: string | null;
  workspaceId: string;
  workspaceRootDigest: string;
  input: ArtifactRef;
  roleAssignments: RoleAssignment[];
  qualificationTraces: QualificationTrace[];
  requirementTraces: RoleRequirementTrace[];
  openObligations: OpenObligation[];
  stateReasons: StateReason[];
  queryGroupExecutions: QueryGroupExecution[];
  queryExecutions: RuntimeQueryExecution[];
  artifacts: RuntimeArtifactMetadata[];
  counts: RuntimeCounts;
  processingSummary: RuntimeProcessingSummary;
  journalDigest: string;
};

export type RuntimeProcessingSummary = {
  availableTimezones: string[];
  timezone: string;
  timezoneAction: string;
  rowsBeforeTimezoneHandling: number;
  rowsAfterTimezoneHandling: number;
  rowsRemovedByTimezone: number;
  timezoneRetainedSourceRowsDigest: string;
  timezoneStageDigest: string;
  workflowQueryGroupDigests: Record<string, string>;
  workflowQueryGroupCheckpoints: Record<string, WorkflowCheckpoint>;
  workflowQueryDigests: Record<string, string>;
  workflowQueryCheckpoints: Record<string, WorkflowCheckpoint>;
  publishedOutputsDigest: string;
  provenanceDigest: string;
  duplicateTimestampsCorrected: number;
  exactDuplicateRowsRemoved: number;
};

export type RuntimeQueryExecution = {
  query_id: string;
  query_group_id: string;
  status: ExecutionStatus;
  input_key: string;
  output_digest: string;
  reason_id: string;
};

export type StateReason = {
  reason_id: string;
  subject_id: string;
  state: MaterializationState;
  source_id: string;
  message: string;
};

export type WorkflowCheckpoint = {
  protocolVersion: string;
  subjectId: string;
  rowMembershipDigest: string;
  rowOrderDigest: string;
  temporalStateDigest: string;
  classificationDigest: string;
  payloadDigest: string;
  schemaDigest: string;
  terminalDigest: string;
};

export const RUNTIME_BOUNDARY_MODEL: BoundaryModel = {
  "protocolVersion": "chronicle-runtime-boundary-model/v1",
  "roots": {
    "reviewRuntimeManifest": "ReviewRuntimeManifest",
    "runtimeManifest": "RuntimeManifest"
  },
  "types": {
    "ArtifactRef": {
      "fields": [
        {
          "name": "artifact_id",
          "rustName": "artifact_id",
          "value": {
            "kind": "string"
          }
        },
        {
          "name": "digest",
          "rustName": "digest",
          "value": {
            "kind": "sha256Digest"
          }
        },
        {
          "name": "media_type",
          "rustName": "media_type",
          "value": {
            "kind": "string"
          }
        },
        {
          "name": "size",
          "rustName": "size",
          "value": {
            "kind": "integer"
          }
        },
        {
          "name": "derived_from",
          "rustName": "derived_from",
          "value": {
            "items": {
              "kind": "string"
            },
            "kind": "array"
          }
        },
        {
          "name": "qualifiers",
          "rustName": "qualifiers",
          "value": {
            "kind": "map",
            "values": {
              "kind": "string"
            }
          }
        }
      ],
      "kind": "struct"
    },
    "DependencyCacheDecision": {
      "fields": [
        {
          "name": "mode",
          "rustName": "mode",
          "value": {
            "kind": "enum",
            "name": "DependencyCacheMode"
          }
        },
        {
          "name": "certificate_digest",
          "rustName": "certificate_digest",
          "value": {
            "inner": {
              "kind": "sha256Digest"
            },
            "kind": "nullable"
          }
        },
        {
          "name": "binding_surface_digest",
          "rustName": "binding_surface_digest",
          "value": {
            "inner": {
              "kind": "sha256Digest"
            },
            "kind": "nullable"
          }
        },
        {
          "name": "empirical_evidence_current",
          "rustName": "empirical_evidence_current",
          "value": {
            "kind": "boolean"
          }
        },
        {
          "name": "reasons",
          "rustName": "reasons",
          "value": {
            "items": {
              "kind": "string"
            },
            "kind": "array"
          }
        }
      ],
      "kind": "struct"
    },
    "DependencyCacheMode": {
      "kind": "enum",
      "label": "dependency cache mode",
      "variants": [
        "certified_narrow",
        "conservative_full"
      ]
    },
    "ExecutionStatus": {
      "kind": "enum",
      "label": "execution status",
      "variants": [
        "cached",
        "recomputed",
        "error",
        "skipped",
        "bypassed"
      ]
    },
    "MaterializationState": {
      "kind": "enum",
      "label": "materialization state",
      "variants": [
        "open",
        "ready",
        "satisfied",
        "blocked",
        "invalid",
        "not_applicable"
      ]
    },
    "OpenObligation": {
      "fields": [
        {
          "name": "obligation_id",
          "rustName": "obligation_id",
          "value": {
            "kind": "string"
          }
        },
        {
          "name": "role_id",
          "rustName": "role_id",
          "value": {
            "kind": "string"
          }
        },
        {
          "name": "query_group_id",
          "rustName": "query_group_id",
          "value": {
            "inner": {
              "kind": "string"
            },
            "kind": "nullable"
          }
        },
        {
          "name": "state",
          "rustName": "state",
          "value": {
            "kind": "enum",
            "name": "MaterializationState"
          }
        },
        {
          "name": "reason_id",
          "rustName": "reason_id",
          "value": {
            "kind": "string"
          }
        }
      ],
      "kind": "struct"
    },
    "QualificationDecision": {
      "kind": "enum",
      "label": "qualification decision",
      "variants": [
        "accepted",
        "rejected",
        "ambiguous"
      ]
    },
    "QualificationRuleEvaluation": {
      "fields": [
        {
          "name": "rule_id",
          "rustName": "rule_id",
          "value": {
            "kind": "string"
          }
        },
        {
          "name": "passed",
          "rustName": "passed",
          "value": {
            "kind": "boolean"
          }
        },
        {
          "name": "expected",
          "rustName": "expected",
          "value": {
            "kind": "string"
          }
        },
        {
          "name": "observed",
          "rustName": "observed",
          "value": {
            "kind": "string"
          }
        }
      ],
      "kind": "struct"
    },
    "QualificationTrace": {
      "fields": [
        {
          "name": "trace_id",
          "rustName": "trace_id",
          "value": {
            "kind": "string"
          }
        },
        {
          "name": "candidate_id",
          "rustName": "candidate_id",
          "value": {
            "kind": "string"
          }
        },
        {
          "name": "candidate_revision",
          "rustName": "candidate_revision",
          "value": {
            "kind": "integer"
          }
        },
        {
          "name": "artifact_digest",
          "rustName": "artifact_digest",
          "value": {
            "kind": "sha256Digest"
          }
        },
        {
          "name": "qualifiers_digest",
          "rustName": "qualifiers_digest",
          "value": {
            "kind": "sha256Digest"
          }
        },
        {
          "name": "asserted_role_ids",
          "rustName": "asserted_role_ids",
          "value": {
            "items": {
              "kind": "string"
            },
            "kind": "array"
          }
        },
        {
          "name": "selected_role_id",
          "rustName": "selected_role_id",
          "value": {
            "inner": {
              "kind": "string"
            },
            "kind": "nullable"
          }
        },
        {
          "name": "decision",
          "rustName": "decision",
          "value": {
            "kind": "enum",
            "name": "QualificationDecision"
          }
        },
        {
          "name": "rule_evaluations",
          "rustName": "rule_evaluations",
          "value": {
            "items": {
              "kind": "struct",
              "name": "QualificationRuleEvaluation"
            },
            "kind": "array"
          }
        },
        {
          "name": "reason_id",
          "rustName": "reason_id",
          "value": {
            "kind": "string"
          }
        }
      ],
      "kind": "struct"
    },
    "QueryGroupExecution": {
      "fields": [
        {
          "name": "query_group_id",
          "rustName": "query_group_id",
          "value": {
            "kind": "string"
          }
        },
        {
          "name": "capability_id",
          "rustName": "capability_id",
          "value": {
            "kind": "string"
          }
        },
        {
          "name": "status",
          "rustName": "status",
          "value": {
            "kind": "enum",
            "name": "ExecutionStatus"
          }
        },
        {
          "name": "input_key",
          "rustName": "input_key",
          "value": {
            "kind": "sha256Digest"
          }
        },
        {
          "name": "output",
          "rustName": "output",
          "value": {
            "inner": {
              "kind": "struct",
              "name": "ArtifactRef"
            },
            "kind": "nullable"
          }
        },
        {
          "name": "reason_id",
          "rustName": "reason_id",
          "value": {
            "kind": "string"
          }
        }
      ],
      "kind": "struct"
    },
    "ReviewRuntimeManifest": {
      "fields": [
        {
          "name": "protocolVersion",
          "rustName": "protocol_version",
          "value": {
            "kind": "string"
          }
        },
        {
          "name": "preprocessorVersion",
          "rustName": "preprocessor_version",
          "value": {
            "kind": "string"
          }
        },
        {
          "name": "requestId",
          "rustName": "request_id",
          "value": {
            "kind": "string"
          }
        },
        {
          "name": "command",
          "rustName": "command",
          "value": {
            "kind": "string"
          }
        },
        {
          "name": "workspaceId",
          "rustName": "workspace_id",
          "value": {
            "kind": "sha256Digest"
          }
        },
        {
          "name": "previousWorkspaceRootDigest",
          "rustName": "previous_workspace_root_digest",
          "value": {
            "inner": {
              "kind": "sha256Digest"
            },
            "kind": "nullable"
          }
        },
        {
          "name": "inputDigest",
          "rustName": "input_digest",
          "value": {
            "kind": "sha256Digest"
          }
        },
        {
          "name": "optionsDigest",
          "rustName": "options_digest",
          "value": {
            "kind": "sha256Digest"
          }
        },
        {
          "name": "implementationDigest",
          "rustName": "implementation_digest",
          "value": {
            "kind": "sha256Digest"
          }
        },
        {
          "name": "buildEnvironmentDigest",
          "rustName": "build_environment_digest",
          "value": {
            "kind": "sha256Digest"
          }
        },
        {
          "name": "planDigest",
          "rustName": "plan_digest",
          "value": {
            "kind": "sha256Digest"
          }
        },
        {
          "name": "profileDigest",
          "rustName": "profile_digest",
          "value": {
            "kind": "sha256Digest"
          }
        },
        {
          "name": "profileLockDigest",
          "rustName": "profile_lock_digest",
          "value": {
            "kind": "sha256Digest"
          }
        },
        {
          "name": "productContractDigest",
          "rustName": "product_contract_digest",
          "value": {
            "kind": "sha256Digest"
          }
        },
        {
          "name": "dependencyCertificateDigest",
          "rustName": "dependency_certificate_digest",
          "value": {
            "kind": "sha256Digest"
          }
        },
        {
          "name": "dependencyCacheDecision",
          "rustName": "dependency_cache_decision",
          "value": {
            "kind": "struct",
            "name": "DependencyCacheDecision"
          }
        },
        {
          "name": "counts",
          "rustName": "counts",
          "value": {
            "kind": "struct",
            "name": "RuntimeCounts"
          }
        },
        {
          "name": "availableTimezones",
          "rustName": "available_timezones",
          "value": {
            "items": {
              "kind": "string"
            },
            "kind": "array"
          }
        },
        {
          "name": "timezone",
          "rustName": "timezone",
          "value": {
            "kind": "string"
          }
        },
        {
          "name": "timezoneAction",
          "rustName": "timezone_action",
          "value": {
            "kind": "string"
          }
        },
        {
          "name": "rowsBeforeTimezoneHandling",
          "rustName": "rows_before_timezone_handling",
          "value": {
            "kind": "integer"
          }
        },
        {
          "name": "rowsAfterTimezoneHandling",
          "rustName": "rows_after_timezone_handling",
          "value": {
            "kind": "integer"
          }
        },
        {
          "name": "rowsRemovedByTimezone",
          "rustName": "rows_removed_by_timezone",
          "value": {
            "kind": "integer"
          }
        },
        {
          "name": "duplicateTimestampsCorrected",
          "rustName": "duplicate_timestamps_corrected",
          "value": {
            "kind": "integer"
          }
        },
        {
          "name": "exactDuplicateRowsRemoved",
          "rustName": "exact_duplicate_rows_removed",
          "value": {
            "kind": "integer"
          }
        },
        {
          "name": "queryGroupExecutions",
          "rustName": "query_group_executions",
          "value": {
            "items": {
              "kind": "struct",
              "name": "QueryGroupExecution"
            },
            "kind": "array"
          }
        },
        {
          "name": "queryExecutions",
          "rustName": "query_executions",
          "value": {
            "items": {
              "kind": "struct",
              "name": "RuntimeQueryExecution"
            },
            "kind": "array"
          }
        },
        {
          "name": "cacheSources",
          "rustName": "cache_sources",
          "value": {
            "items": {
              "kind": "string"
            },
            "kind": "array"
          }
        },
        {
          "name": "reviewSummaryDigest",
          "rustName": "review_summary_digest",
          "value": {
            "kind": "sha256Digest"
          }
        },
        {
          "name": "comparisonDigest",
          "rustName": "comparison_digest",
          "value": {
            "kind": "sha256Digest"
          }
        },
        {
          "name": "reviewSummaryReused",
          "rustName": "review_summary_reused",
          "value": {
            "kind": "boolean"
          }
        }
      ],
      "kind": "struct"
    },
    "RoleAssignment": {
      "fields": [
        {
          "name": "assignment_id",
          "rustName": "assignment_id",
          "value": {
            "kind": "string"
          }
        },
        {
          "name": "role_id",
          "rustName": "role_id",
          "value": {
            "kind": "string"
          }
        },
        {
          "name": "artifact",
          "rustName": "artifact",
          "value": {
            "kind": "struct",
            "name": "ArtifactRef"
          }
        },
        {
          "name": "qualifiers",
          "rustName": "qualifiers",
          "value": {
            "kind": "map",
            "values": {
              "kind": "string"
            }
          }
        },
        {
          "name": "revision",
          "rustName": "revision",
          "value": {
            "kind": "integer"
          }
        }
      ],
      "kind": "struct"
    },
    "RoleRequirementTrace": {
      "fields": [
        {
          "name": "trace_id",
          "rustName": "trace_id",
          "value": {
            "kind": "string"
          }
        },
        {
          "name": "role_id",
          "rustName": "role_id",
          "value": {
            "kind": "string"
          }
        },
        {
          "name": "required",
          "rustName": "required",
          "value": {
            "kind": "boolean"
          }
        },
        {
          "name": "unconditional",
          "rustName": "unconditional",
          "value": {
            "kind": "boolean"
          }
        },
        {
          "name": "condition_id",
          "rustName": "condition_id",
          "value": {
            "inner": {
              "kind": "string"
            },
            "kind": "nullable"
          }
        },
        {
          "name": "condition_result",
          "rustName": "condition_result",
          "value": {
            "inner": {
              "kind": "boolean"
            },
            "kind": "nullable"
          }
        },
        {
          "name": "candidate_trace_ids",
          "rustName": "candidate_trace_ids",
          "value": {
            "items": {
              "kind": "string"
            },
            "kind": "array"
          }
        },
        {
          "name": "accepted_assignment_ids",
          "rustName": "accepted_assignment_ids",
          "value": {
            "items": {
              "kind": "string"
            },
            "kind": "array"
          }
        },
        {
          "name": "state",
          "rustName": "state",
          "value": {
            "kind": "enum",
            "name": "MaterializationState"
          }
        },
        {
          "name": "reason_id",
          "rustName": "reason_id",
          "value": {
            "kind": "string"
          }
        }
      ],
      "kind": "struct"
    },
    "RuntimeArtifactMetadata": {
      "fields": [
        {
          "name": "artifactId",
          "rustName": "artifact_id",
          "value": {
            "kind": "string"
          }
        },
        {
          "name": "kind",
          "rustName": "kind",
          "value": {
            "kind": "string"
          }
        },
        {
          "name": "mediaType",
          "rustName": "media_type",
          "value": {
            "kind": "string"
          }
        },
        {
          "name": "digest",
          "rustName": "digest",
          "value": {
            "kind": "sha256Digest"
          }
        },
        {
          "name": "size",
          "rustName": "size",
          "value": {
            "kind": "integer"
          }
        },
        {
          "name": "derivedFrom",
          "rustName": "derived_from",
          "value": {
            "items": {
              "kind": "string"
            },
            "kind": "array"
          }
        },
        {
          "name": "rowCount",
          "optional": true,
          "rustName": "row_count",
          "value": {
            "kind": "integer"
          }
        },
        {
          "name": "previewRows",
          "optional": true,
          "rustName": "preview_rows",
          "value": {
            "items": {
              "items": {
                "kind": "looseString"
              },
              "kind": "array"
            },
            "kind": "array"
          }
        }
      ],
      "kind": "struct"
    },
    "RuntimeCounts": {
      "fields": [
        {
          "name": "original",
          "rustName": "original",
          "value": {
            "kind": "integer"
          }
        },
        {
          "name": "processed",
          "rustName": "processed",
          "value": {
            "kind": "integer"
          }
        },
        {
          "name": "app",
          "rustName": "app",
          "value": {
            "kind": "integer"
          }
        },
        {
          "name": "screen",
          "rustName": "screen",
          "value": {
            "kind": "integer"
          }
        }
      ],
      "kind": "struct"
    },
    "RuntimeManifest": {
      "fields": [
        {
          "name": "protocolVersion",
          "rustName": "protocol_version",
          "value": {
            "kind": "string"
          }
        },
        {
          "name": "preprocessorVersion",
          "rustName": "preprocessor_version",
          "value": {
            "kind": "string"
          }
        },
        {
          "name": "requestId",
          "rustName": "request_id",
          "value": {
            "kind": "string"
          }
        },
        {
          "name": "command",
          "rustName": "command",
          "value": {
            "kind": "string"
          }
        },
        {
          "name": "implementation",
          "rustName": "implementation",
          "value": {
            "kind": "string"
          }
        },
        {
          "name": "implementationDigest",
          "rustName": "implementation_digest",
          "value": {
            "kind": "sha256Digest"
          }
        },
        {
          "name": "buildEnvironmentDigest",
          "rustName": "build_environment_digest",
          "value": {
            "kind": "sha256Digest"
          }
        },
        {
          "name": "scope",
          "rustName": "scope",
          "value": {
            "kind": "string"
          }
        },
        {
          "name": "planDigest",
          "rustName": "plan_digest",
          "value": {
            "kind": "sha256Digest"
          }
        },
        {
          "name": "profileDigest",
          "rustName": "profile_digest",
          "value": {
            "kind": "sha256Digest"
          }
        },
        {
          "name": "profileLockDigest",
          "rustName": "profile_lock_digest",
          "value": {
            "kind": "sha256Digest"
          }
        },
        {
          "name": "runtimeAuthorityDigest",
          "rustName": "runtime_authority_digest",
          "value": {
            "kind": "sha256Digest"
          }
        },
        {
          "name": "productContractDigest",
          "rustName": "product_contract_digest",
          "value": {
            "kind": "sha256Digest"
          }
        },
        {
          "name": "dependencyCertificateDigest",
          "rustName": "dependency_certificate_digest",
          "value": {
            "kind": "sha256Digest"
          }
        },
        {
          "name": "dependencyCacheDecision",
          "rustName": "dependency_cache_decision",
          "value": {
            "kind": "struct",
            "name": "DependencyCacheDecision"
          }
        },
        {
          "name": "previousWorkspaceRootDigest",
          "rustName": "previous_workspace_root_digest",
          "value": {
            "inner": {
              "kind": "sha256Digest"
            },
            "kind": "nullable"
          }
        },
        {
          "name": "workspaceId",
          "rustName": "workspace_id",
          "value": {
            "kind": "sha256Digest"
          }
        },
        {
          "name": "workspaceRootDigest",
          "rustName": "workspace_root_digest",
          "value": {
            "kind": "sha256Digest"
          }
        },
        {
          "name": "input",
          "rustName": "input",
          "value": {
            "kind": "struct",
            "name": "ArtifactRef"
          }
        },
        {
          "name": "roleAssignments",
          "rustName": "role_assignments",
          "value": {
            "items": {
              "kind": "struct",
              "name": "RoleAssignment"
            },
            "kind": "array"
          }
        },
        {
          "name": "qualificationTraces",
          "rustName": "qualification_traces",
          "value": {
            "items": {
              "kind": "struct",
              "name": "QualificationTrace"
            },
            "kind": "array"
          }
        },
        {
          "name": "requirementTraces",
          "rustName": "requirement_traces",
          "value": {
            "items": {
              "kind": "struct",
              "name": "RoleRequirementTrace"
            },
            "kind": "array"
          }
        },
        {
          "name": "openObligations",
          "rustName": "open_obligations",
          "value": {
            "items": {
              "kind": "struct",
              "name": "OpenObligation"
            },
            "kind": "array"
          }
        },
        {
          "name": "stateReasons",
          "rustName": "state_reasons",
          "value": {
            "items": {
              "kind": "struct",
              "name": "StateReason"
            },
            "kind": "array"
          }
        },
        {
          "name": "queryGroupExecutions",
          "rustName": "query_group_executions",
          "value": {
            "items": {
              "kind": "struct",
              "name": "QueryGroupExecution"
            },
            "kind": "array"
          }
        },
        {
          "name": "queryExecutions",
          "rustName": "query_executions",
          "value": {
            "items": {
              "kind": "struct",
              "name": "RuntimeQueryExecution"
            },
            "kind": "array"
          }
        },
        {
          "name": "artifacts",
          "rustName": "artifacts",
          "value": {
            "items": {
              "kind": "struct",
              "name": "RuntimeArtifactMetadata"
            },
            "kind": "array"
          }
        },
        {
          "name": "counts",
          "rustName": "counts",
          "value": {
            "kind": "struct",
            "name": "RuntimeCounts"
          }
        },
        {
          "name": "processingSummary",
          "rustName": "processing_summary",
          "value": {
            "kind": "struct",
            "name": "RuntimeProcessingSummary"
          }
        },
        {
          "name": "journalDigest",
          "rustName": "journal_digest",
          "value": {
            "kind": "sha256Digest"
          }
        }
      ],
      "kind": "struct"
    },
    "RuntimeProcessingSummary": {
      "fields": [
        {
          "name": "availableTimezones",
          "rustName": "available_timezones",
          "value": {
            "items": {
              "kind": "string"
            },
            "kind": "array"
          }
        },
        {
          "name": "timezone",
          "rustName": "timezone",
          "value": {
            "kind": "string"
          }
        },
        {
          "name": "timezoneAction",
          "rustName": "timezone_action",
          "value": {
            "kind": "string"
          }
        },
        {
          "name": "rowsBeforeTimezoneHandling",
          "rustName": "rows_before_timezone_handling",
          "value": {
            "kind": "integer"
          }
        },
        {
          "name": "rowsAfterTimezoneHandling",
          "rustName": "rows_after_timezone_handling",
          "value": {
            "kind": "integer"
          }
        },
        {
          "name": "rowsRemovedByTimezone",
          "rustName": "rows_removed_by_timezone",
          "value": {
            "kind": "integer"
          }
        },
        {
          "name": "timezoneRetainedSourceRowsDigest",
          "rustName": "timezone_retained_source_rows_digest",
          "value": {
            "kind": "sha256Digest"
          }
        },
        {
          "name": "timezoneStageDigest",
          "rustName": "timezone_stage_digest",
          "value": {
            "kind": "sha256Digest"
          }
        },
        {
          "name": "workflowQueryGroupDigests",
          "rustName": "workflow_query_group_digests",
          "value": {
            "kind": "map",
            "values": {
              "kind": "sha256Digest"
            }
          }
        },
        {
          "name": "workflowQueryGroupCheckpoints",
          "rustName": "workflow_query_group_checkpoints",
          "value": {
            "kind": "map",
            "values": {
              "kind": "struct",
              "name": "WorkflowCheckpoint"
            }
          }
        },
        {
          "name": "workflowQueryDigests",
          "rustName": "workflow_query_digests",
          "value": {
            "kind": "map",
            "values": {
              "kind": "sha256Digest"
            }
          }
        },
        {
          "name": "workflowQueryCheckpoints",
          "rustName": "workflow_query_checkpoints",
          "value": {
            "kind": "map",
            "values": {
              "kind": "struct",
              "name": "WorkflowCheckpoint"
            }
          }
        },
        {
          "name": "publishedOutputsDigest",
          "rustName": "published_outputs_digest",
          "value": {
            "kind": "sha256Digest"
          }
        },
        {
          "name": "provenanceDigest",
          "rustName": "provenance_digest",
          "value": {
            "kind": "sha256Digest"
          }
        },
        {
          "name": "duplicateTimestampsCorrected",
          "rustName": "duplicate_timestamps_corrected",
          "value": {
            "kind": "integer"
          }
        },
        {
          "name": "exactDuplicateRowsRemoved",
          "rustName": "exact_duplicate_rows_removed",
          "value": {
            "kind": "integer"
          }
        }
      ],
      "kind": "struct"
    },
    "RuntimeQueryExecution": {
      "fields": [
        {
          "name": "query_id",
          "rustName": "query_id",
          "value": {
            "kind": "string"
          }
        },
        {
          "name": "query_group_id",
          "rustName": "query_group_id",
          "value": {
            "kind": "string"
          }
        },
        {
          "name": "status",
          "rustName": "status",
          "value": {
            "kind": "enum",
            "name": "ExecutionStatus"
          }
        },
        {
          "name": "input_key",
          "rustName": "input_key",
          "value": {
            "kind": "sha256Digest"
          }
        },
        {
          "name": "output_digest",
          "rustName": "output_digest",
          "value": {
            "kind": "sha256Digest"
          }
        },
        {
          "name": "reason_id",
          "rustName": "reason_id",
          "value": {
            "kind": "sha256Digest"
          }
        }
      ],
      "kind": "struct"
    },
    "StateReason": {
      "fields": [
        {
          "name": "reason_id",
          "rustName": "reason_id",
          "value": {
            "kind": "string"
          }
        },
        {
          "name": "subject_id",
          "rustName": "subject_id",
          "value": {
            "kind": "string"
          }
        },
        {
          "name": "state",
          "rustName": "state",
          "value": {
            "kind": "enum",
            "name": "MaterializationState"
          }
        },
        {
          "name": "source_id",
          "rustName": "source_id",
          "value": {
            "kind": "string"
          }
        },
        {
          "name": "message",
          "rustName": "message",
          "value": {
            "kind": "string"
          }
        }
      ],
      "kind": "struct"
    },
    "WorkflowCheckpoint": {
      "fields": [
        {
          "name": "protocolVersion",
          "rustName": "protocol_version",
          "value": {
            "kind": "string"
          }
        },
        {
          "name": "subjectId",
          "rustName": "subject_id",
          "value": {
            "kind": "string"
          }
        },
        {
          "name": "rowMembershipDigest",
          "rustName": "row_membership_digest",
          "value": {
            "kind": "string"
          }
        },
        {
          "name": "rowOrderDigest",
          "rustName": "row_order_digest",
          "value": {
            "kind": "string"
          }
        },
        {
          "name": "temporalStateDigest",
          "rustName": "temporal_state_digest",
          "value": {
            "kind": "string"
          }
        },
        {
          "name": "classificationDigest",
          "rustName": "classification_digest",
          "value": {
            "kind": "string"
          }
        },
        {
          "name": "payloadDigest",
          "rustName": "payload_digest",
          "value": {
            "kind": "string"
          }
        },
        {
          "name": "schemaDigest",
          "rustName": "schema_digest",
          "value": {
            "kind": "string"
          }
        },
        {
          "name": "terminalDigest",
          "rustName": "terminal_digest",
          "value": {
            "kind": "string"
          }
        }
      ],
      "kind": "struct"
    }
  }
};
