use chronicle_chrono_kernel_wasm::pipeline_v2::PipelineV2OptionsJson;
use chronicle_preprocessing_runtime_wasm::literature_input_adapters::{
    adapt_literature_inputs, literature_component_execution_unit,
};
use chronicle_preprocessing_runtime_wasm::{
    execute_literature_component_native, RuntimeArtifactMetadata, RuntimeRequest,
    RuntimeSupportFiles, EXECUTE_WORKSPACE_COMMAND, RUNTIME_PROTOCOL_VERSION,
};
use serde_json::json;
use sha2::{Digest, Sha256};

const COMPONENT_ID: &str = "chronicle.notification-payload-cleaning/v1";

fn sha256(bytes: &[u8]) -> String {
    format!("sha256:{}", hex::encode(Sha256::digest(bytes)))
}

fn options() -> PipelineV2OptionsJson {
    serde_json::from_value(json!({
        "study_name": "Released notification payload cleaning",
        "timezone": "UTC",
        "usage_session_mode": "app_usage",
        "include_app_output": true,
        "include_screen_output": false,
        "use_filter_file": false,
        "use_apps_forcing_screen_open": false,
        "use_app_codebook": false,
        "correct_duplicate_event_timestamps": false,
        "allow_stop_event_reuse": false,
        "use_activity_stopped_as_fallback": true,
        "apply_threshold_to_fallback": true,
        "long_duration_threshold_ns": 43_200_000_000_000_i64,
        "custom_app_engagement_duration": 300.0,
        "long_data_time_gap_thresholds": [1.0, 2.0],
        "long_usage_duration_thresholds": [1.0, 2.0],
        "same_app_stop_types": ["Activity Paused", "Activity Resumed"],
        "other_stop_types": ["Activity Resumed", "Device Shutdown"],
        "interaction_types_to_remove": [],
        "screen_auto_lock_timeout_seconds": 120.0,
        "screen_auto_lock_tolerance_seconds": 30.0,
        "screen_manual_lock_max_tail_seconds": 30.0,
        "screen_keyguard_near_stop_seconds": 2.0,
        "datetime_of_preprocessing": "2026-09-03 00:00:00 UTC",
        "minimum_usage_duration": 0.0
    }))
    .expect("valid component options")
}

fn request(raw: &[u8]) -> String {
    serde_json::to_string(&RuntimeRequest {
        protocol_version: RUNTIME_PROTOCOL_VERSION.into(),
        request_id: "notification-payload-cleaning".into(),
        command: EXECUTE_WORKSPACE_COMMAND.into(),
        workspace_root_digest: None,
        workspace_id: sha256(b"notification-payload-cleaning-workspace"),
        input_file_name: "notification-rows.csv".into(),
        input_sha256: sha256(raw),
        known_review_summary_digests: None,
        participant_partition_batch_id: None,
        fragmented_participant_tokens: Vec::new(),
        method_profile_receipt: None,
        method_profile_receipts: Vec::new(),
        execution_engine: chronicle_preprocessing_runtime_wasm::ExecutionEngine::Sequential,
        provenance_evidence: false,
        options: options(),
    })
    .expect("request JSON")
}

fn adapter_error(raw: &[u8]) -> String {
    let (_, bindings) = literature_component_execution_unit(COMPONENT_ID).expect("registration");
    match adapt_literature_inputs(raw, &sha256(raw), &bindings, |_| &[]) {
        Err(error) => error,
        Ok(_) => panic!("expected fail-closed adapter error"),
    }
}


fn execute(component: &str, raw: &[u8], result_kind: &str) -> (serde_json::Value, Vec<u8>) {
    let mut handle = execute_literature_component_native(
        component, &request(raw), raw, &RuntimeSupportFiles::default(),
    ).expect("public registered component execution");
    let manifest = serde_json::from_str(&handle.manifest_json()).expect("manifest");
    let mut result = None;
    for index in 0..handle.artifact_count() {
        let metadata: RuntimeArtifactMetadata =
            serde_json::from_str(&handle.artifact_metadata_json(index).expect("metadata"))
                .expect("typed metadata");
        let bytes = handle.take_artifact_bytes(index).expect("artifact");
        assert_eq!(metadata.digest, sha256(&bytes));
        if metadata.kind == result_kind { result = Some(bytes); }
    }
    (manifest, result.expect("derived result"))
}

fn table(bytes: &[u8]) -> (csv::StringRecord, Vec<csv::StringRecord>) {
    let mut reader = csv::Reader::from_reader(bytes);
    let headers = reader.headers().expect("header").clone();
    let rows = reader.records().map(|row| row.expect("row")).collect();
    (headers, rows)
}

#[test]
fn released_payload_cleaning_matches_isolated_r_for_all_79_patterns_and_character_boundaries() {
    // Generated by retained isolated base-R oracle from the pinned source AST.
    // Its synthetic inputs include each of the 79 literal, wildcard, newline and case probes.
    let input = include_bytes!("fixtures/notification_payload_cleaning_source_input.csv");
    let expected = include_bytes!("fixtures/notification_payload_cleaning_source_expected.csv");
    let patterns = include_bytes!("fixtures/notification_payload_cleaning_source_patterns.csv");
    assert_eq!(table(patterns).1.len(), 79);
    let (registration, bindings) = literature_component_execution_unit(COMPONENT_ID).expect("registration");
    assert_eq!(bindings.len(), 5);
    assert!(registration.required_support_roles.is_empty());
    assert_eq!(registration.full_profile_execution_status, "blocked");
    let (manifest, output) = execute(COMPONENT_ID, input, "literature-notification-payload-cleaning-csv");
    assert_eq!(manifest["sourceRowCount"], table(input).1.len());
    assert_eq!(manifest["derivedResultRowCount"], table(expected).1.len());
    // CSV quoting is carrier-specific; compare every actual field, order and duplicate.
    assert_eq!(table(&output), table(expected));
}

#[test]
fn released_payload_contract_rejects_unrepresentable_dates_and_missing_fields_without_reinterpreting_empty() {
    for time in ["", "2023-02-29 00:00:00", "2024-13-01", "2024/02/29", "2024-2-29"] {
        let raw = format!("source_row_id,Code,Time,Data\nr,P1,{time},\n");
        assert!(adapter_error(raw.as_bytes()).contains("valid canonical YYYY-MM-DD prefix"), "{time:?}");
    }
    assert!(adapter_error(b"source_row_id,Code,Time\nr,P1,2024-02-29\n")
        .contains("requires raw column Data"));
    assert!(adapter_error(b"source_row_id,Code,Time,Data,Data\nr,P1,2024-02-29,,\n")
        .contains("refuses duplicate column names"));
    assert!(adapter_error(b"source_row_id,Code,Time,Data\nr,,2024-02-29,\n")
        .contains("nonempty source_row_id and Code"));
    let raw = b"source_row_id,Code,Time,Data\nr,P1,2024-02-29,\n";
    let (_, output) = execute(COMPONENT_ID, raw, "literature-notification-payload-cleaning-csv");
    let (headers, rows) = table(&output);
    let column = |name| headers.iter().position(|field| field == name).expect("column");
    assert_eq!(rows.len(), 1);
    assert_eq!(&rows[0][column("app")], "");
    assert_eq!(&rows[0][column("time")], "");
    assert_eq!(&rows[0][column("Time")], "2024-02-29");
    assert_eq!(&rows[0][column("study_week")], "");
    assert_eq!(&rows[0][column("tracking_date_observed")], "false");
}

#[test]
fn cleaned_notification_rows_feed_existing_daily_counter_only_with_caller_owned_day_spine() {
    let raw = concat!(
        "source_row_id,Code,Time,Data,study_week,intervention_group\n",
        "n1,P1,2024-02-29 12:00:00,XOrdinary App123456textprivate,0,0\n",
        "n2,P1,2024-02-29 12:00:01,XOrdinary App123456textprivate,0,0\n",
        "drop,P1,2024-02-29 12:00:02,XAndroid-System123456textprivate,0,0\n",
    ).as_bytes();
    let (_, cleaned) = execute(COMPONENT_ID, raw, "literature-notification-payload-cleaning-csv");
    let daily_id = "chronicle.notification-study-daily/v1";
    let (_, daily_bindings) = literature_component_execution_unit(daily_id).expect("existing daily registration");
    let unspined = adapt_literature_inputs(&cleaned, &sha256(&cleaned), &daily_bindings, |_| &[]);
    assert!(matches!(unspined, Err(error) if error.contains("at least one participant-day spine row")));

    // Explicit study inputs, not dates inferred from observed notifications:
    // two caller-owned eligible days, with no notification on the second day.
    let (headers, rows) = table(&cleaned);
    let mut writer = csv::Writer::from_writer(Vec::new());
    writer.write_record(&headers).expect("header");
    for row in rows { writer.write_record(&row).expect("cleaned row"); }
    for (date, week) in [("2024-02-29", "0"), ("2024-03-01", "1")] {
        let event_timestamp = format!("{date} 00:00:00");
        let values: Vec<_> = headers.iter().map(|field| match field {
            "participant_id" => "P1",
            "event_timestamp" => event_timestamp.as_str(),
            "interaction_type" => "Tracking Day",
            "study_local_date" => date,
            "study_week" => week,
            "intervention_group" => "0",
            "tracking_date_observed" => "true",
            "notification_observed" => "false",
            _ => "",
        }).collect();
        writer.write_record(values).expect("supplied spine row");
    }
    let input = writer.into_inner().expect("daily input");
    let (_, output) = execute(daily_id, &input, "literature-notification-daily-count-source-variants-csv");
    let (headers, rows) = table(&output);
    let column = |name| headers.iter().position(|field| field == name).expect("column");
    let counts: Vec<_> = rows.iter().map(|row| (
        row[column("variant_id")].to_owned(),
        row[column("study_local_date")].to_owned(),
        row[column("daily_contact_count")].to_owned(),
    )).collect();
    assert_eq!(counts, vec![
        ("released-code-joined-row-count".into(), "2024-02-29".into(), "2".into()),
        ("released-code-joined-row-count".into(), "2024-03-01".into(), "1".into()),
        ("stated-intended-zero-fill".into(), "2024-02-29".into(), "2".into()),
        ("stated-intended-zero-fill".into(), "2024-03-01".into(), "0".into()),
    ]);
}
