#!/usr/bin/env node
// Generate a realistic ~500-row raw Chronicle CSV that ships as the
// "Demo a sample file" payload. Properly paired Activity Resumed /
// Paused / Stopped events, a sprinkling of system events (keyguard,
// screen-interactive), one timezone, multi-day, multiple apps. Output
// is written to web/src/lib/sampleRawCsv.ts as a literal string so the
// JS bundle is hermetic.

import { writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, resolve } from "node:path";

const here = dirname(fileURLToPath(import.meta.url));
const outFile = resolve(here, "..", "src", "lib", "sampleRawCsv.ts");

const HEADERS = [
  "study_id",
  "participant_id",
  "possible_device_model",
  "username",
  "application_label",
  "interaction_type",
  "app_package_name",
  "event_timestamp",
  "start_timestamp",
  "stop_timestamp",
  "timezone",
];

const APPS = [
  { label: "Spotify", pkg: "com.spotify.music" },
  { label: "YouTube", pkg: "com.google.android.youtube" },
  { label: "Maps", pkg: "com.google.android.apps.maps" },
  { label: "Chrome", pkg: "com.android.chrome" },
  { label: "Messages", pkg: "com.google.android.apps.messaging" },
  { label: "Calendar", pkg: "com.google.android.calendar" },
  { label: "Photos", pkg: "com.google.android.apps.photos" },
  { label: "Instagram", pkg: "com.instagram.android" },
];

const SEED = 0xc0ffee;
/** @param {number} seed */
function rng(seed) {
  let s = seed >>> 0;
  return () => {
    s = Math.imul(s ^ (s >>> 16), 2246822507);
    s = Math.imul(s ^ (s >>> 13), 3266489909);
    s = (s ^ (s >>> 16)) >>> 0;
    return s / 0xffffffff;
  };
}

const rand = rng(SEED);
const TIMEZONE = "America/Chicago";
const PARTICIPANT = "P0001";

/** @param {number} ms */
function fmt(ms) {
  const d = new Date(ms);
  const pad = (/** @type {number} */ n) => String(n).padStart(2, "0");
  return `${d.getUTCFullYear()}-${pad(d.getUTCMonth() + 1)}-${pad(d.getUTCDate())} ${pad(
    d.getUTCHours(),
  )}:${pad(d.getUTCMinutes())}:${pad(d.getUTCSeconds())}`;
}

/** @param {Array<string | number | null | undefined>} values */
function row(values) {
  return values.map((v) => (v == null ? "" : String(v))).join(",");
}

const TARGET_ROWS = 600;
const rows = [HEADERS.join(",")];

let cursor = Date.UTC(2026, 1, 16, 6, 0, 0); // 2026-02-16 06:00:00 UTC
let openApp = null;

while (rows.length - 1 < TARGET_ROWS) {
  const r = rand();
  if (openApp) {
    const closeType = r < 0.85 ? "Unknown importance: 2" : "Unknown importance: 23";
    rows.push(
      row([
        "demo",
        PARTICIPANT,
        "Android",
        "Target Child",
        openApp.label,
        closeType,
        openApp.pkg,
        fmt(cursor),
        "",
        "",
        TIMEZONE,
      ]),
    );
    openApp = null;
  } else if (r < 0.08) {
    // Keyguard / screen-interactive system event — exercises the screen-usage path.
    const events = [
      "Unknown importance: 17", // Keyguard Shown
      "Unknown importance: 18", // Keyguard Hidden
      "Unknown importance: 15", // Screen Interactive
      "Unknown importance: 16", // Screen Non-Interactive
    ];
    rows.push(
      row([
        "demo",
        PARTICIPANT,
        "Android",
        "Target Child",
        "System",
        events[Math.floor(rand() * events.length)],
        "android",
        fmt(cursor),
        "",
        "",
        TIMEZONE,
      ]),
    );
  } else {
    const app = APPS[Math.floor(rand() * APPS.length)];
    rows.push(
      row([
        "demo",
        PARTICIPANT,
        "Android",
        "Target Child",
        app.label,
        "Unknown importance: 1",
        app.pkg,
        fmt(cursor),
        "",
        "",
        TIMEZONE,
      ]),
    );
    openApp = app;
  }
  // Time advance: 30s to 12 min between events
  cursor += Math.floor(rand() * 12 * 60_000) + 30_000;
}
if (openApp) {
  cursor += 60_000;
  rows.push(
    row([
      "demo",
      PARTICIPANT,
      "Android",
      "Target Child",
      openApp.label,
      "Unknown importance: 2",
      openApp.pkg,
      fmt(cursor),
      "",
      "",
      TIMEZONE,
    ]),
  );
}

const csv = rows.join("\n") + "\n";
const fileContents = `// Generated by web/scripts/generate_sample_raw_csv.mjs — do not edit by hand.
// Re-run \`node web/scripts/generate_sample_raw_csv.mjs\` to refresh.

export const SAMPLE_FILE_NAME = "Demo Chronicle Raw.csv";

export const sampleRawCsv = ${JSON.stringify(csv)};
`;

writeFileSync(outFile, fileContents);
console.log(`wrote ${outFile} (${rows.length - 1} data rows, ${csv.length} bytes)`);
