// Output-column codebook: bijection check + researcher-facing artifact
// (docs/workflow/dag-validate-ontologize-productize-research.md O2 + P1).
//
//   vite-node scripts/generate_output_codebook_artifacts.mts           # write
//   vite-node scripts/generate_output_codebook_artifacts.mts --check   # drift gate
//
// The emit-order SSOT is exported directly by the Rust pipeline.
// web/schema/chronicle-output-columns.yaml is the hand-authored
// semantics layer. This script enforces the bijection between the two and
// renders docs/researcher-output-codebook.md from the catalog.

import { readFile, writeFile } from "node:fs/promises";
import { execFileSync } from "node:child_process";
import path from "node:path";
import process from "node:process";
import { fileURLToPath } from "node:url";

import { parse as parseYaml } from "yaml";

const HERE = path.dirname(fileURLToPath(import.meta.url));
const CATALOG_PATH = path.resolve(HERE, "../schema/chronicle-output-columns.yaml");
const CODEBOOK_PATH = path.resolve(HERE, "../../docs/researcher-output-codebook.md");
const RUST_MANIFEST_PATH = path.resolve(
  HERE,
  "../../rust/chronicle_chrono_kernel_wasm/Cargo.toml",
);

type CatalogEntry = {
  column_name: string;
  column_outputs: string[];
  value_type: string;
  units?: string;
  column_description: string;
  present_when?: string;
  filter_dependent?: boolean;
  vocabulary_alignment?: string;
};

/** Replace the option-stamped header suffix with its catalog placeholder. */
function normalizeColumnName(column: string): string {
  return column.replace(
    /_custom_[0-9.eE+-]+s$/,
    "_custom_{custom_app_engagement_duration}s",
  );
}

function rustOutputColumns(): { app: Set<string>; screen: Set<string> } {
  const output = execFileSync(
    "cargo",
    [
      "run",
      "--quiet",
      "--locked",
      "--manifest-path",
      RUST_MANIFEST_PATH,
      "--bin",
      "export_output_column_contract",
    ],
    { encoding: "utf-8" },
  );
  const contract = JSON.parse(output) as {
    protocolVersion: string;
    app: string[];
    screen: string[];
  };
  if (contract.protocolVersion !== "chronicle-output-column-contract/v1") {
    throw new Error(`Unsupported Rust output-column contract: ${contract.protocolVersion}`);
  }
  return {
    app: new Set(contract.app.map(normalizeColumnName)),
    screen: new Set(contract.screen),
  };
}

async function loadCatalog(): Promise<CatalogEntry[]> {
  const doc = parseYaml(await readFile(CATALOG_PATH, "utf-8")) as { output_columns: CatalogEntry[] };
  if (!Array.isArray(doc.output_columns)) throw new Error("catalog missing output_columns list");
  return doc.output_columns;
}

function checkBijection(catalog: CatalogEntry[]): void {
  const rustColumns = rustOutputColumns();
  const expected = new Map<string, Set<string>>([
    ["app", rustColumns.app],
    ["screen", rustColumns.screen],
  ]);
  const catalogByOutput = new Map<string, Set<string>>([
    ["app", new Set()],
    ["screen", new Set()],
  ]);
  const seen = new Set<string>();
  for (const entry of catalog) {
    if (seen.has(entry.column_name)) throw new Error(`duplicate catalog entry: ${entry.column_name}`);
    seen.add(entry.column_name);
    for (const output of entry.column_outputs) {
      const bucket = catalogByOutput.get(output);
      if (!bucket) throw new Error(`${entry.column_name}: unknown output kind "${output}"`);
      bucket.add(entry.column_name);
    }
  }
  for (const [output, expectedColumns] of expected) {
    const catalogColumns = catalogByOutput.get(output)!;
    for (const column of expectedColumns) {
      if (!catalogColumns.has(column)) {
        throw new Error(`code emits ${output} column "${column}" with no catalog entry`);
      }
    }
    for (const column of catalogColumns) {
      if (!expectedColumns.has(column)) {
        throw new Error(`catalog lists ${output} column "${column}" the code never emits`);
      }
    }
  }
}

function renderCodebook(catalog: CatalogEntry[]): string {
  const lines: string[] = [
    "# Researcher codebook — delivered output columns",
    "",
    "<!-- GENERATED by web/scripts/generate_output_codebook_artifacts.mts from",
    "     web/schema/chronicle-output-columns.yaml — do not edit by hand. -->",
    "",
    "Column-by-column semantics of the App Usage and Screen Usage CSVs the",
    "preprocessor delivers. Names in `{braces}` are stamped with the option",
    "value at processing time. \"Present when\" refers to processing options",
    "(snake_case names as in the settings contract); blank means the column is",
    "always present. Columns marked *filter-dependent* are defined over the",
    "non-filtered app universe, so enabling the filter file legitimately",
    "changes their values.",
    "",
  ];
  for (const output of ["app", "screen"] as const) {
    lines.push(`## ${output === "app" ? "App Usage" : "Screen Usage"} output`, "");
    lines.push("| Column | Type | Units | Present when | Description |");
    lines.push("|--------|------|-------|--------------|-------------|");
    for (const entry of catalog) {
      if (!entry.column_outputs.includes(output)) continue;
      const description = [
        entry.column_description.trim().replace(/\s+/g, " "),
        entry.filter_dependent ? "*Filter-dependent.*" : "",
        entry.vocabulary_alignment ? `*Vocabulary: ${entry.vocabulary_alignment}.*` : "",
      ]
        .filter(Boolean)
        .join(" ");
      lines.push(
        `| \`${entry.column_name}\` | ${entry.value_type} | ${entry.units ?? ""} | ${entry.present_when ?? ""} | ${description} |`,
      );
    }
    lines.push("");
  }
  return `${lines.join("\n")}`;
}

async function main(): Promise<void> {
  const check = process.argv.includes("--check");
  const catalog = await loadCatalog();
  checkBijection(catalog);
  const rendered = renderCodebook(catalog);
  if (check) {
    const existing = await readFile(CODEBOOK_PATH, "utf-8").catch(() => null);
    if (existing !== rendered) {
      console.error(
        `DRIFT: ${path.relative(process.cwd(), CODEBOOK_PATH)} out of date — regenerate with: ` +
          "vite-node scripts/generate_output_codebook_artifacts.mts",
      );
      process.exit(1);
    }
    console.log(JSON.stringify({ status: "ok", mode: "check", artifact: "docs/researcher-output-codebook.md" }));
    return;
  }
  await writeFile(CODEBOOK_PATH, rendered, "utf-8");
  console.log(`wrote ${CODEBOOK_PATH} (${catalog.length} columns)`);
}

main().catch((error) => {
  console.error(error);
  process.exit(1);
});
