// Output-column codebook: bijection check + researcher-facing artifact
// (docs/dag-validate-ontologize-productize-research.md O2 + P1).
//
//   vite-node scripts/generate_output_codebook_artifacts.mts           # write
//   vite-node scripts/generate_output_codebook_artifacts.mts --check   # drift gate
//
// The emit-order SSOT is buildAppOutputColumns / buildScreenOutputColumns in
// browserPipeline.ts (evaluated over every option combination that changes the
// column set). web/schema/chronicle-output-columns.yaml is the hand-authored
// semantics layer. This script enforces the bijection between the two and
// renders docs/researcher-output-codebook.md from the catalog.

import { readFile, writeFile } from "node:fs/promises";
import path from "node:path";
import process from "node:process";
import { fileURLToPath } from "node:url";

import { parse as parseYaml } from "yaml";

import { buildAppOutputColumns, buildScreenOutputColumns } from "../src/lib/browserPipeline";
import { DEFAULT_BROWSER_OPTIONS } from "../src/lib/generatedContract";
import type { BrowserProcessingOptions } from "../src/lib/types";

const HERE = path.dirname(fileURLToPath(import.meta.url));
const CATALOG_PATH = path.resolve(HERE, "../schema/chronicle-output-columns.yaml");
const CODEBOOK_PATH = path.resolve(HERE, "../../docs/researcher-output-codebook.md");

type CatalogEntry = {
  column_name: string;
  column_outputs: string[];
  value_type: string;
  units?: string;
  column_description: string;
  present_when?: string;
  filter_dependent?: boolean;
  vocabulary_alignment?: string;
};

/** Replace the option-stamped header suffix with its catalog placeholder. */
function normalizeColumnName(column: string): string {
  return column.replace(
    new RegExp(`_custom_${DEFAULT_BROWSER_OPTIONS.customAppEngagementDuration}s$`),
    "_custom_{custom_app_engagement_duration}s",
  );
}

/** Every column the app CSV can emit, across the option combos that change the set. */
function emittedAppColumns(): Set<string> {
  const columns = new Set<string>();
  for (const useAppCodebook of [false, true]) {
    for (const includeCategoryColumn of [false, true]) {
      for (const usageLayerActive of [false, true]) {
        const options: BrowserProcessingOptions = {
          ...DEFAULT_BROWSER_OPTIONS,
          useAppCodebook,
          includeCategoryColumn,
        };
        for (const includeCodebookAliases of [false, true]) {
          for (const column of buildAppOutputColumns(options, includeCodebookAliases, usageLayerActive)) {
            columns.add(normalizeColumnName(column));
          }
        }
      }
    }
  }
  return columns;
}

async function loadCatalog(): Promise<CatalogEntry[]> {
  const doc = parseYaml(await readFile(CATALOG_PATH, "utf-8")) as { output_columns: CatalogEntry[] };
  if (!Array.isArray(doc.output_columns)) throw new Error("catalog missing output_columns list");
  return doc.output_columns;
}

function checkBijection(catalog: CatalogEntry[]): void {
  const expected = new Map<string, Set<string>>([
    ["app", emittedAppColumns()],
    ["screen", new Set(buildScreenOutputColumns())],
  ]);
  const catalogByOutput = new Map<string, Set<string>>([
    ["app", new Set()],
    ["screen", new Set()],
  ]);
  const seen = new Set<string>();
  for (const entry of catalog) {
    if (seen.has(entry.column_name)) throw new Error(`duplicate catalog entry: ${entry.column_name}`);
    seen.add(entry.column_name);
    for (const output of entry.column_outputs) {
      const bucket = catalogByOutput.get(output);
      if (!bucket) throw new Error(`${entry.column_name}: unknown output kind "${output}"`);
      bucket.add(entry.column_name);
    }
  }
  for (const [output, expectedColumns] of expected) {
    const catalogColumns = catalogByOutput.get(output)!;
    for (const column of expectedColumns) {
      if (!catalogColumns.has(column)) {
        throw new Error(`code emits ${output} column "${column}" with no catalog entry`);
      }
    }
    for (const column of catalogColumns) {
      if (!expectedColumns.has(column)) {
        throw new Error(`catalog lists ${output} column "${column}" the code never emits`);
      }
    }
  }
}

function renderCodebook(catalog: CatalogEntry[]): string {
  const lines: string[] = [
    "# Researcher codebook — delivered output columns",
    "",
    "<!-- GENERATED by web/scripts/generate_output_codebook_artifacts.mts from",
    "     web/schema/chronicle-output-columns.yaml — do not edit by hand. -->",
    "",
    "Column-by-column semantics of the App Usage and Screen Usage CSVs the",
    "preprocessor delivers. Names in `{braces}` are stamped with the option",
    "value at processing time. \"Present when\" refers to processing options",
    "(snake_case names as in the settings contract); blank means the column is",
    "always present. Columns marked *filter-dependent* are defined over the",
    "non-filtered app universe, so enabling the filter file legitimately",
    "changes their values.",
    "",
  ];
  for (const output of ["app", "screen"] as const) {
    lines.push(`## ${output === "app" ? "App Usage" : "Screen Usage"} output`, "");
    lines.push("| Column | Type | Units | Present when | Description |");
    lines.push("|--------|------|-------|--------------|-------------|");
    for (const entry of catalog) {
      if (!entry.column_outputs.includes(output)) continue;
      const description = [
        entry.column_description.trim().replace(/\s+/g, " "),
        entry.filter_dependent ? "*Filter-dependent.*" : "",
        entry.vocabulary_alignment ? `*Vocabulary: ${entry.vocabulary_alignment}.*` : "",
      ]
        .filter(Boolean)
        .join(" ");
      lines.push(
        `| \`${entry.column_name}\` | ${entry.value_type} | ${entry.units ?? ""} | ${entry.present_when ?? ""} | ${description} |`,
      );
    }
    lines.push("");
  }
  return `${lines.join("\n")}`;
}

async function main(): Promise<void> {
  const check = process.argv.includes("--check");
  const catalog = await loadCatalog();
  checkBijection(catalog);
  const rendered = renderCodebook(catalog);
  if (check) {
    const existing = await readFile(CODEBOOK_PATH, "utf-8").catch(() => null);
    if (existing !== rendered) {
      console.error(
        `DRIFT: ${path.relative(process.cwd(), CODEBOOK_PATH)} out of date — regenerate with: ` +
          "vite-node scripts/generate_output_codebook_artifacts.mts",
      );
      process.exit(1);
    }
    console.log(JSON.stringify({ status: "ok", mode: "check", artifact: "docs/researcher-output-codebook.md" }));
    return;
  }
  await writeFile(CODEBOOK_PATH, rendered, "utf-8");
  console.log(`wrote ${CODEBOOK_PATH} (${catalog.length} columns)`);
}

main().catch((error) => {
  console.error(error);
  process.exit(1);
});
