// Writes web/third-party/rust-wasm-crates.txt: the license and NOTICE texts of
// every third-party Rust crate statically linked into the two browser WASM
// packages that `npm run build:wasm` produces.
//
// The crate set is the normal-dependency closure of each WASM crate, resolved by
// `cargo metadata --filter-platform wasm32-unknown-unknown` against the
// committed Cargo.lock files. Build- and dev-dependencies, and proc-macro
// crates with everything only they pull in, run on the build host and are not
// linked into the WASM, so they are excluded. Vendored third-party crates
// (rust/chronicle_preprocessing_runtime_wasm/vendor/arrow-ipc-*) are included.
//
// Texts are read from each crate's published source: LICENSE*, LICENCE*,
// COPYING*, NOTICE*, COPYRIGHT*, UNLICENSE*, plus the manifest's
// `license-file`. A crate from a git checkout that ships none in its own
// directory takes the files at the nearest parent up to the checkout root,
// where workspace repositories keep them. Identical license texts are printed
// once with the crates that carry them; NOTICE files (Apache-2.0 section 4(d))
// are printed per crate.
//
// The deploy runner cannot resolve the private semantic-profile-toolchain
// crates, so this output is committed next to the committed WASM packages and
// regenerated by build:wasm; `make wasm-fresh` fails when it drifts.
//
// Usage: node scripts/rust_wasm_notices.mjs [--check]
import { execFileSync } from "node:child_process";
import { createHash } from "node:crypto";
import { readFileSync, readdirSync, statSync, writeFileSync } from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const webRoot = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const repositoryRoot = path.resolve(webRoot, "..");
const outputPath = path.join(webRoot, "third-party", "rust-wasm-crates.txt");
const WASM_CRATES = [
  "chronicle_preprocessing_runtime_wasm",
  "chronicle_semantic_index_wasm",
];
const LICENSE_FILE = /^(licen[cs]e|copying|notice|copyright|unlicense)/i;
const NOTICE_FILE = /^notice/i;
const GIT_CHECKOUT_ROOT = /^(.*[\\/]git[\\/]checkouts[\\/][^\\/]+[\\/][^\\/]+)/;

/**
 * @typedef {{id: string, name: string, version: string, license: string | null, license_file: string | null, repository: string | null, source: string | null, manifest_path: string, targets: Array<{kind: string[]}>}} CargoPackage
 * @typedef {{id: string, deps: Array<{pkg: string, dep_kinds: Array<{kind: string | null}>}>}} CargoNode
 * @typedef {{packages: CargoPackage[], resolve: {root: string, nodes: CargoNode[]}}} CargoMetadata
 */

/**
 * @param {string} crate
 * @returns {CargoMetadata}
 */
function metadata(crate) {
  const stdout = execFileSync(
    "cargo",
    [
      "metadata",
      "--format-version",
      "1",
      "--locked",
      "--filter-platform",
      "wasm32-unknown-unknown",
      "--manifest-path",
      path.join(repositoryRoot, "rust", crate, "Cargo.toml"),
    ],
    { encoding: "utf8", maxBuffer: 256 * 1024 * 1024, stdio: ["ignore", "pipe", "inherit"] },
  );
  return JSON.parse(stdout);
}

/** @param {string} directory */
function licenseFilesIn(directory) {
  return readdirSync(directory).filter(
    (name) => LICENSE_FILE.test(name) && statSync(path.join(directory, name)).isFile(),
  );
}

/**
 * Packages keyed by `name@version`, so a crate reached from both WASM roots is
 * listed once.
 * @type {Map<string, {name: string, version: string, license: string | null, repository: string | null, source: string | null, directory: string, licenseFile: string | null}>}
 */
const packages = new Map();
for (const crate of WASM_CRATES) {
  const meta = metadata(crate);
  const byId = new Map(meta.packages.map((pkg) => [pkg.id, pkg]));
  const nodes = new Map(meta.resolve.nodes.map((node) => [node.id, node]));
  /** @param {string} id */
  const packageOf = (id) => {
    const pkg = byId.get(id);
    if (!pkg) throw new Error(`cargo metadata names unknown package ${id}`);
    return pkg;
  };
  /** @type {Set<string>} */
  const reached = new Set();
  const stack = [meta.resolve.root];
  for (let id = stack.pop(); id !== undefined; id = stack.pop()) {
    if (reached.has(id)) continue;
    const pkg = packageOf(id);
    if (pkg.targets.some((target) => target.kind.includes("proc-macro"))) continue;
    reached.add(id);
    for (const dep of nodes.get(id)?.deps ?? []) {
      if (dep.dep_kinds.some((kind) => kind.kind === null)) stack.push(dep.pkg);
    }
  }
  for (const id of reached) {
    const pkg = packageOf(id);
    const directory = path.dirname(pkg.manifest_path);
    // This repository's own crates are the GPL-3.0-only application itself.
    if (
      pkg.name.startsWith("chronicle_") &&
      !path.relative(repositoryRoot, directory).startsWith("..")
    ) {
      continue;
    }
    packages.set(`${pkg.name}@${pkg.version}`, {
      name: pkg.name,
      version: pkg.version,
      license: pkg.license,
      repository: pkg.repository,
      source: pkg.source,
      directory,
      licenseFile: pkg.license_file,
    });
  }
}

const sorted = [...packages.values()].sort(
  (left, right) =>
    left.name.localeCompare(right.name) || left.version.localeCompare(right.version),
);
/** @type {Map<string, {text: string, files: Set<string>, crates: string[]}>} */
const licenseTexts = new Map();
/** @type {Array<{crate: string, file: string, text: string}>} */
const notices = [];
const withoutTexts = [];
for (const pkg of sorted) {
  let licenseDirectory = pkg.directory;
  let found = licenseFilesIn(licenseDirectory);
  const checkoutRoot = pkg.source?.startsWith("git+")
    ? GIT_CHECKOUT_ROOT.exec(pkg.directory)?.[1]
    : undefined;
  while (found.length === 0 && checkoutRoot && licenseDirectory !== checkoutRoot) {
    licenseDirectory = path.dirname(licenseDirectory);
    found = licenseFilesIn(licenseDirectory);
  }
  const files = new Set(found);
  if (pkg.licenseFile) {
    files.add(path.relative(licenseDirectory, path.resolve(pkg.directory, pkg.licenseFile)));
  }
  const crate = `${pkg.name} ${pkg.version}`;
  if (files.size === 0) withoutTexts.push(pkg);
  for (const file of [...files].sort()) {
    const text = readFileSync(path.join(licenseDirectory, file), "utf8")
      .replace(/\r\n/g, "\n")
      // Trailing spaces carry no meaning and the repository strips them.
      .replace(/[ \t]+$/gm, "")
      .trimEnd();
    if (NOTICE_FILE.test(file)) {
      notices.push({ crate, file, text });
      continue;
    }
    const digest = createHash("sha256").update(text).digest("hex");
    const group = licenseTexts.get(digest) ?? { text, files: new Set(), crates: [] };
    group.files.add(file);
    group.crates.push(crate);
    licenseTexts.set(digest, group);
  }
}

const rule = "=".repeat(78);
const lines = [
  "Rust crates linked into the Chronicle WebAssembly packages",
  "",
  "Generated by web/scripts/rust_wasm_notices.mjs from the committed Cargo.lock",
  "files (normal dependencies, target wasm32-unknown-unknown). Do not edit.",
  "",
  `${sorted.length} crates:`,
  "",
  ...sorted.map(
    (pkg) =>
      `  ${pkg.name} ${pkg.version}  [${pkg.license ?? "license-file only"}]${pkg.repository ? `  ${pkg.repository}` : ""}`,
  ),
  "",
];
if (withoutTexts.length > 0) {
  lines.push(
    "These crates publish no license file in their package. Each is licensed",
    "under the SPDX expression listed above, whose standard text appears below",
    "where another crate ships it.",
    "",
    ...withoutTexts.map((pkg) => `  ${pkg.name} ${pkg.version}  [${pkg.license}]`),
    "",
  );
}
lines.push(rule, "NOTICE files (reproduced verbatim as Apache-2.0 section 4(d) requires)", rule, "");
for (const notice of notices) {
  lines.push(`--- ${notice.crate}: ${notice.file} ---`, "", notice.text, "");
}
lines.push(rule, "License texts", rule, "");
const groups = [...licenseTexts.values()].sort((left, right) =>
  (left.crates[0] ?? "").localeCompare(right.crates[0] ?? ""),
);
for (const group of groups) {
  lines.push(
    `--- ${[...group.files].sort().join(", ")} ---`,
    `Used by: ${group.crates.join(", ")}`,
    "",
    group.text,
    "",
  );
}
const output = `${lines.join("\n").trimEnd()}\n`;

if (process.argv.includes("--check")) {
  let committed = "";
  try {
    committed = readFileSync(outputPath, "utf8");
  } catch {
    // A missing file is reported as stale below.
  }
  if (committed !== output) {
    console.error(
      `${path.relative(repositoryRoot, outputPath)} is stale; run node web/scripts/rust_wasm_notices.mjs`,
    );
    process.exit(1);
  }
  console.log(`${path.relative(repositoryRoot, outputPath)} is current (${sorted.length} crates)`);
} else {
  writeFileSync(outputPath, output);
  console.log(
    JSON.stringify({
      output: path.relative(repositoryRoot, outputPath),
      crates: sorted.length,
      distinctLicenseTexts: groups.length,
      noticeFiles: notices.map((notice) => notice.crate),
      cratesWithoutLicenseFile: withoutTexts.map((pkg) => `${pkg.name} ${pkg.version}`),
    }),
  );
}
