import type { RuntimeManifest } from "@/lib/generatedRuntimeBoundary";

/** Shared observation layer for the dependency-tomography campaigns.
 *
 * Every campaign reads the SAME document — the JSON emitted by
 * `RuntimeExecutionHandle::manifest_json()` in
 * `chronicle_preprocessing_runtime_wasm` — and every campaign used to declare
 * its own near-identical structural type for it plus its own copies of the
 * handful of projections over it. Five drifting descriptions of one document
 * is how a campaign silently stops observing the field it thinks it reads, so
 * there is one description here and the campaigns import it.
 *
 * This module is deliberately observation-only: it knows nothing about the
 * published workflow contract (that lives in `workflowContract.ts`) and makes
 * no claim about what SHOULD have executed. */

/** The manifest the campaigns observe IS the product's runtime manifest, and
 * `generatedRuntimeBoundary.ts` already carries a Rust-derived description of
 * it (generated by
 * `rust/chronicle_preprocessing_runtime_wasm/examples/boundary_model.rs`,
 * verified by `npm run check:boundary`). Aliasing it — instead of hand-writing
 * a sixth structural copy — is what makes a change to the Rust serialization
 * model break the campaigns at compile time rather than silently. */
export type CampaignRuntimeManifest = RuntimeManifest;

/** A manifest paired with the canonical output cells captured from the same
 * handle (`captureCanonicalOutputCells`). Three campaigns declared this exact
 * intersection separately — two as `ObservedRuntimeManifest`, one as
 * `Observation`. */
export type ObservedRuntimeManifest = CampaignRuntimeManifest & {
  outputCells: Record<string, string>;
};

/** Plan root roles the runtime qualifies only when a conditionally reached
 * branch demands them, so a campaign that never activates that branch produces
 * no qualification trace for them and must not compare per-case trace counts
 * against the plan's full root-role list.
 *
 * `input_capability_evidence_file` is the only such role today: the browser
 * offers it only when `usesInputCapabilityEvidence(options)` holds
 * (`web/src/lib/inputCapabilityEvidence.ts`) and
 * `putScientificCampaignSupportArtifact` drops it for every other
 * configuration. The runtime reports that shape by construction rather than by
 * omission — `qualify_assignments` builds one `QualificationTrace` per offered
 * candidate and one `RoleRequirementTrace` per plan root role, scoring an
 * optional role with no accepted candidate as
 * `MaterializationState::NotApplicable`. Its source-sensitive coverage is owned
 * by the configuration-space campaign's `sourceSensitiveScientificCells`
 * domain. */
export const CONDITIONALLY_ACTIVE_ROOT_ROLE_IDS: readonly string[] = [
  "input_capability_evidence_file",
];

/** The plan root roles a campaign running only unconditional configurations
 * must see qualified, in plan order. */
export function unconditionalRootRoleIds(
  rootRoles: ReadonlyArray<{ role_id: string }>,
): string[] {
  return rootRoles
    .map(({ role_id }) => role_id)
    .filter((roleId) => !CONDITIONALLY_ACTIVE_ROOT_ROLE_IDS.includes(roleId));
}

/** Keys whose JSON-serialized values differ between two documents. */
export function changedFields(
  left: Record<string, unknown>,
  right: Record<string, unknown>,
): string[] {
  return [...new Set([...Object.keys(left), ...Object.keys(right)])]
    .filter((key) => JSON.stringify(left[key]) !== JSON.stringify(right[key]))
    .sort();
}

/** Physical execution status per registered Rust query. */
export function queryStatuses(
  manifest: CampaignRuntimeManifest,
): Record<string, string> {
  return Object.fromEntries(
    manifest.queryExecutions.map(({ query_id, status }) => [query_id, status]),
  );
}

/** The queries whose bodies physically ran in this request, sorted. */
export function executedQueryIds(manifest: CampaignRuntimeManifest): string[] {
  return manifest.queryExecutions
    .filter(({ status }) => status === "recomputed")
    .map(({ query_id }) => query_id)
    .sort();
}

/** Published output digest per registered Rust query. */
export function queryOutputDigests(
  manifest: CampaignRuntimeManifest,
): Record<string, string> {
  return Object.fromEntries(
    manifest.queryExecutions.map(({ query_id, output_digest }) => [
      query_id,
      output_digest,
    ]),
  );
}

/** Logical output digest per query group, `null` when the group published none. */
export function nodeOutputDigests(
  manifest: CampaignRuntimeManifest,
): Record<string, string | null> {
  return Object.fromEntries(
    manifest.queryGroupExecutions.map(({ query_group_id, output }) => [
      query_group_id,
      output?.digest ?? null,
    ]),
  );
}

/** Queries the warm target badged `cached` while publishing an output digest
 * that moved from the warm source.
 *
 * A Salsa body produces a new value only by running, so this set must be empty
 * for a real memo. The check reads only two observed digests and the observed
 * status — never the published `inputs` declaration — so it stays true whatever
 * the declaration says. It is what fails when a request executes a query
 * outside the window the runtime measures: the scientific preflight forces the
 * whole `construct_screen_intervals` ancestor closure before `execute` opens
 * its own window, and reporting only that window badged thirteen stages reused
 * in a run that recomputed them. */
export function cachedWithChangedOutput(
  warmSource: CampaignRuntimeManifest,
  warmTarget: CampaignRuntimeManifest,
): string[] {
  const sourceOutputs = queryOutputDigests(warmSource);
  return warmTarget.queryExecutions
    .filter(({ status, query_id, output_digest }) => {
      if (status !== "cached") return false;
      if (sourceOutputs[query_id] === undefined) {
        // The runtime enumerates every WORKFLOW_QUERIES member with a digest
        // (inapplicability is a status, never an absence), so a missing source
        // entry means the manifests disagree about the registry -- fail loud
        // instead of silently skipping the drift check for this query.
        throw new Error(
          `warm source manifest has no output digest for query ${query_id}`,
        );
      }
      return sourceOutputs[query_id] !== output_digest;
    })
    .map(({ query_id }) => query_id)
    .sort();
}

/** Researcher-visible result artifacts. Aggregate exports are matched by the
 * `aggregate-` prefix; the kernel emits a closed set of six literal
 * aggregate kinds (build_aggregate_outputs in pipeline_v2_aggregates.rs),
 * each at most once per run, so kind is a unique artifact key. */
export const OUTPUT_ARTIFACT_KINDS: ReadonlySet<string> = new Set([
  "app-csv",
  "screen-csv",
  "day-coverage-csv",
  "compliance-csv",
  "credited-app-csv",
  "notification-contact-csv",
  "polled-emulation-csv",
  "review-summary-json",
  "visualization-data-json",
  "app-parquet",
  "screen-parquet",
  "app-spss",
  "screen-spss",
  "row-lineage-arrow",
  "source-coordinate-index-arrow",
  "result-cell-correspondence-arrow",
  "source-result-influence-arrow",
]);

/** Whether an emitted artifact kind is a researcher-visible output. */
export function isOutputArtifactKind(kind: string): boolean {
  return OUTPUT_ARTIFACT_KINDS.has(kind) || kind.startsWith("aggregate-");
}

/** Digest per researcher-visible output artifact kind, kind-sorted. */
export function outputArtifactDigests(
  manifest: CampaignRuntimeManifest,
): Record<string, string> {
  return Object.fromEntries(
    manifest.artifacts
      .filter(({ kind }) => isOutputArtifactKind(kind))
      .sort((left, right) => left.kind.localeCompare(right.kind))
      .map(({ kind, digest }) => [kind, digest]),
  );
}

/** The implementation identity every case in a campaign must agree on. Any
 * drift means two cases were produced by different builds and cannot be
 * compared. */
export function authorityReceipt(
  manifest: CampaignRuntimeManifest,
): Record<string, string> {
  return {
    implementation: manifest.implementation,
    implementationDigest: manifest.implementationDigest,
    planDigest: manifest.planDigest,
    profileDigest: manifest.profileDigest,
    profileLockDigest: manifest.profileLockDigest,
    runtimeAuthorityDigest: manifest.runtimeAuthorityDigest,
    productContractDigest: manifest.productContractDigest,
  };
}

/** Changed typed checkpoint components per query GROUP, keyed by node id, with
 * groups whose components all agree omitted. `terminalDigest` is excluded: it
 * is the commitment the other components produce, so reporting it would
 * double-count every change.
 *
 * KEY ORDER is the sorted node id. One of the four callers previously iterated
 * the plan's `order` instead, which put the same entries in plan order in its
 * recorded ledger; the ledgers are re-recorded alongside this consolidation, so
 * every campaign now records sorted keys. */
export function changedCheckpointComponents(
  source: CampaignRuntimeManifest,
  target: CampaignRuntimeManifest,
): Record<string, string[]> {
  return Object.fromEntries(
    Object.keys(source.processingSummary.workflowQueryGroupCheckpoints)
      .sort()
      .map(
        (nodeId) =>
          [
            nodeId,
            changedFields(
              source.processingSummary.workflowQueryGroupCheckpoints[nodeId] ??
                {},
              target.processingSummary.workflowQueryGroupCheckpoints[nodeId] ??
                {},
            ).filter((component) => component !== "terminalDigest"),
          ] as const,
      )
      .filter(([, components]) => components.length > 0),
  );
}

/** Changed typed checkpoint components per QUERY, keyed by query id, with
 * queries whose components all agree omitted. Same `terminalDigest` exclusion
 * and same sorted key order as `changedCheckpointComponents`. */
export function changedQueryCheckpointComponents(
  source: CampaignRuntimeManifest,
  target: CampaignRuntimeManifest,
): Record<string, string[]> {
  return Object.fromEntries(
    Object.keys(source.processingSummary.workflowQueryCheckpoints)
      .sort()
      .map(
        (queryId) =>
          [
            queryId,
            changedFields(
              source.processingSummary.workflowQueryCheckpoints[queryId] ?? {},
              target.processingSummary.workflowQueryCheckpoints[queryId] ?? {},
            ).filter((component) => component !== "terminalDigest"),
          ] as const,
      )
      .filter(([, components]) => components.length > 0),
  );
}

/** The same group-level change set as `changedCheckpointComponents`, flattened
 * to `nodeId.component` addresses. */
export function checkpointComponentSet(
  source: CampaignRuntimeManifest,
  target: CampaignRuntimeManifest,
): string[] {
  return Object.entries(changedCheckpointComponents(source, target)).flatMap(
    ([nodeId, components]) =>
      components.map((component) => `${nodeId}.${component}`),
  );
}
