/* tslint:disable */
/* eslint-disable */
export const memory: WebAssembly.Memory;
export const __wbg_preparedreviewworkspace_free: (a: number, b: number) => void;
export const __wbg_runtimehandle_free: (a: number, b: number) => void;
export const __wbg_runtimesupportfiles_free: (a: number, b: number) => void;
export const build_environment_digest: (a: number) => void;
export const discover_timezones_v2: (a: number, b: number, c: number) => void;
export const evaluate_workspace_requirements: (a: number, b: number, c: number, d: number, e: number, f: number) => void;
export const execute_workspace: (a: number, b: number, c: number, d: number, e: number, f: number) => void;
export const execute_workspace_with_review_base: (a: number, b: number, c: number, d: number, e: number, f: number, g: number, h: number) => void;
export const execute_workspace_with_review_bases: (a: number, b: number, c: number, d: number, e: number, f: number, g: number, h: number, i: number, j: number) => void;
export const implementation_build_digest: (a: number) => void;
export const inspect_raw_file_v1: (a: number, b: number, c: number, d: number, e: number, f: number) => void;
export const pipeline_step_contract_json: (a: number) => void;
export const plan_stage_view_json: (a: number, b: number, c: number) => void;
export const prepare_persisted_workspace_review: (a: number, b: number, c: number, d: number, e: number, f: number, g: number, h: number, i: number) => void;
export const prepare_workspace_review: (a: number, b: number, c: number, d: number, e: number, f: number, g: number, h: number, i: number, j: number) => void;
export const preparedreviewworkspace_execute_selected_base: (a: number, b: number, c: number, d: number) => void;
export const preparedreviewworkspace_required_base_kind: (a: number, b: number) => void;
export const review_base_probe_spec_json: (a: number) => void;
export const runtime_identity_json: (a: number) => void;
export const runtime_version: (a: number) => void;
export const runtimehandle_artifact_count: (a: number) => number;
export const runtimehandle_artifact_metadata_json: (a: number, b: number, c: number) => void;
export const runtimehandle_manifest_json: (a: number, b: number) => void;
export const runtimehandle_take_artifact_bytes: (a: number, b: number, c: number) => void;
export const runtimesupportfiles_new: () => number;
export const runtimesupportfiles_put: (a: number, b: number, c: number, d: number, e: number, f: number) => void;
export const runtimesupportfiles_put_with_name: (a: number, b: number, c: number, d: number, e: number, f: number, g: number, h: number) => void;
export const verify_evidence_journal_cbor: (a: number, b: number, c: number) => void;
export const __wbindgen_add_to_stack_pointer: (a: number) => number;
export const __wbindgen_export: (a: number, b: number, c: number) => void;
export const __wbindgen_export2: (a: number, b: number) => number;
export const __wbindgen_export3: (a: number, b: number, c: number, d: number) => number;
